const data = [
{
    'Title': [
        'Vote for TAs' office hour',
        'In-class activity #7 will be on Thursday, Dec. 23rd',
        'Course evaluations for ECE 313',
        'Final exam guidelines',
        'Exam 2 scores posted',
        'Online lectures to continue',
        'Exam 2 guidelines',
        'Exam 2 proctor assignments',
        'Exam 2 will be open book / notes',
        'Exam 2 coverage',
        'Lecture will be online on Monday and Thursday (Dec 13 and Dec 16)',
        'December 9th announcements',
        'Exam 2 postponed (and other announcements)',
        'Correlation, covariance, and correlation coefficient could appear on Exam 2',
        '2 A4 sheets of notes are allowed for Exam 2',
        'Yes, there will be lecture on Tuesday, December 7th',
        'Online lecture meeting information',
        'Exam 1 marking questions: Friday Nov. 19th, 12:30 to 13:30, library cafe',
        'No homework this week',
        'Room change to Lecture Theater West room LTW102',
        'Exam 1 room assignments',
        'Lecture canceled for Monday, Nov. 1st',
        'No homework this week',
        'Exam 1 coverage in Hajek's notes',
        'Exam 1, Tuesday Nov. 2, 19:00 to 21:00',
        'Exam 1 has been rescheduled (again) --- see the new announcement',
        'Exam 1 has been rescheduled --- see the new announcement',
        'Lecture notes updated',
        'QR code for course WeChat group posted',
        'Lecture notes are posted',
        'Please join Piazza',
        'Course syllabus posted',
        'Course evaluations',
        'Lab 1 updated (now using Python 3)',
        'Lab attendance is not required, but contact the instructor / TAs if you have questions',
        'Lab 0 posted',
        'Course syllabus updated',
        'Course syllabus posted',
        'Final Results',
        'Assignment 12 model answers',
        'Last lecture, December 24',
        'Video December 22',
        'Assignment 12, hint',
        'Course Feedback',
        'Mistake in Assignment 11',
        'Teaching in classroom',
        'Video December 17',
        'IMPORTANT: Final Exam',
        'Video December 15',
        'online teaching extended',
        'Video December 10',
        'Lecture THIS Friday',
        'Video December 8',
        'Change to Assignment 11',
        'Change to Assignment 10',
        'Online teaching ends next Wednesday',
        'Video December 3',
        'Video December 1',
        'Lecture tomorrow / December 1',
        'Assignments deadline',
        'Assignment 9',
        'Video November 26',
        'online teaching',
        'Lecture tomorrow online',
        'Video November 24',
        'Video November 19',
        'Lecture Slides 7',
        'Assignment 8 deadline',
        'Video',
        'Assignment 8',
        'Assignment 7 deadline',
        'Video November 12',
        'Video November 10',
        'Video November 5',
        'Video November 3',
        'Midterm Exam (important)',
        'Video October 29',
        'Video October 27',
        'Video October 20',
        'Video October 15',
        'Video October 13',
        'Video October 9',
        'Teaching on campus and online',
        'Assignment 2; hints',
        'Assignment 1; grading',
        'Video September 29',
        'Textbooks',
        'Ass.1, Ex.1',
        'Assignment 1 deadline',
        'Video September 24',
        'Video September 22',
        'Video September 17',
        'Reminder: enroll into discussion groups',
        'Piazza',
        'Video September 15',
        'Reminder: courses are online',
        'zoom for online lectures',
        'Course Start',
        'Reminder - no lecture due to Mid-Autumn Festival on 9/21',
        'ECE385群二维码',
        'New test',
        'Important announcement regarding the final assessments for IE2',
        'Welcome to mid-terms!',
        'Reminder: Homework submissions',
        'Integrated English 2 WeChat Group',
        'Submission errors',
        'Welcome to Spring Semester 2020',
        'Phys213 prelabs',
        'Updated notes',
        'Correction for Midterm Location',
        'Midterm's and lectures schedule',
        'About Midterm',
        'Regrding the Formula Sheet(s)',
        'Lectures schedule arrangement',
        'Lectures begin',
        'classroom of phys214 lab1',
        'Class schedule of phys214 lab',
        'Bonus Points for Final Exam-If you finish the task below',
        'Final Exam',
        'Tentative Schedule of PHY 214 Final Exam',
        'Final EXAM',
        'Reminder: Midterm Exam will be on Friday 6pm-7:20pm',
        'Midterm Term Exam on March 19, 6pm-7:20pm',
        'Midterm Term Exam on March 19, 6pm-7:20pm',
        'Smart Physics System:https://smart.physics.illinois.edu/',
        'survey for conflicts of Final Exam',
        'Office Hour',
        'Discussion material',
        '最后提醒：https://smart.physics.illinois.edu/',
        '形势与政策II讲座通知（4月1日）',
        'Residential College online course collection just open up!'
    ],
    'Posted On': [
        'Thursday, September 16, 2021 12:01:46 PM CST',
        'Tuesday, December 21, 2021 11:15:00 AM CST',
        'Monday, December 20, 2021 4:04:15 PM CST',
        'Monday, December 20, 2021 3:58:33 PM CST',
        'Tuesday, December 21, 2021 8:33:47 AM CST',
        'Monday, December 20, 2021 9:17:14 AM CST',
        'Tuesday, December 14, 2021 8:39:09 AM CST',
        'Tuesday, December 14, 2021 8:23:24 AM CST',
        'Monday, December 13, 2021 5:39:38 PM CST',
        'Sunday, November 28, 2021 1:58:20 PM CST',
        'Monday, December 13, 2021 8:11:10 AM CST',
        'Thursday, December 9, 2021 7:34:53 AM CST',
        'Friday, December 3, 2021 2:57:29 PM CST',
        'Thursday, December 2, 2021 5:12:49 PM CST',
        'Thursday, December 2, 2021 10:19:49 AM CST',
        'Friday, December 3, 2021 2:46:08 PM CST',
        'Monday, November 29, 2021 7:32:00 AM CST',
        'Thursday, November 18, 2021 10:06:06 AM CST',
        'Thursday, November 11, 2021 3:11:14 PM CST',
        'Thursday, November 11, 2021 2:47:51 PM CST',
        'Monday, November 1, 2021 9:06:55 AM CST',
        'Sunday, October 31, 2021 10:55:28 AM CST',
        'Thursday, October 28, 2021 8:56:44 PM CST',
        'Wednesday, October 27, 2021 10:47:38 AM CST',
        'Monday, October 25, 2021 10:31:49 AM CST',
        'Monday, October 25, 2021 7:57:09 AM CST',
        'Wednesday, October 20, 2021 7:32:14 AM CST',
        'Tuesday, September 28, 2021 3:07:18 PM CST',
        'Wednesday, September 22, 2021 1:24:47 PM CST',
        'Monday, September 13, 2021 4:00:55 PM CST',
        'Monday, September 13, 2021 9:29:00 AM CST',
        'Monday, September 13, 2021 9:21:14 AM CST',
        'Monday, December 20, 2021 4:06:17 PM CST',
        'Friday, September 17, 2021 10:03:32 AM CST',
        'Wednesday, September 15, 2021 4:15:40 PM CST',
        'Wednesday, September 15, 2021 4:12:59 PM CST',
        'Wednesday, September 15, 2021 4:11:28 PM CST',
        'Monday, September 13, 2021 9:32:24 AM CST',
        'Tuesday, December 28, 2021 5:39:33 PM CST',
        'Sunday, December 26, 2021 4:37:29 PM CST',
        'Wednesday, December 22, 2021 1:03:40 PM CST',
        'Wednesday, December 22, 2021 1:00:45 PM CST',
        'Tuesday, December 21, 2021 9:57:32 AM CST',
        'Monday, December 20, 2021 7:13:07 PM CST',
        'Sunday, December 19, 2021 10:19:49 PM CST',
        'Sunday, December 19, 2021 5:26:07 PM CST',
        'Friday, December 17, 2021 12:10:27 PM CST',
        'Thursday, December 16, 2021 9:42:33 AM CST',
        'Wednesday, December 15, 2021 12:12:11 PM CST',
        'Monday, December 13, 2021 7:54:24 AM CST',
        'Saturday, December 11, 2021 4:22:50 PM CST',
        'Wednesday, December 8, 2021 10:10:12 PM CST',
        'Wednesday, December 8, 2021 12:59:57 PM CST',
        'Saturday, December 4, 2021 5:25:33 PM CST',
        'Saturday, December 4, 2021 5:20:23 PM CST',
        'Friday, December 3, 2021 2:25:30 PM CST',
        'Friday, December 3, 2021 12:07:32 PM CST',
        'Wednesday, December 1, 2021 2:01:49 PM CST',
        'Tuesday, November 30, 2021 8:17:19 PM CST',
        'Monday, November 29, 2021 8:25:09 PM CST',
        'Monday, November 29, 2021 10:33:17 AM CST',
        'Friday, November 26, 2021 1:13:00 PM CST',
        'Friday, November 26, 2021 8:17:48 AM CST',
        'Thursday, November 25, 2021 9:43:19 PM CST',
        'Wednesday, November 24, 2021 12:57:25 PM CST',
        'Friday, November 19, 2021 1:30:02 PM CST',
        'Thursday, November 18, 2021 9:05:19 AM CST',
        'Wednesday, November 17, 2021 1:30:52 PM CST',
        'Wednesday, November 17, 2021 1:30:17 PM CST',
        'Monday, November 15, 2021 1:29:27 PM CST',
        'Sunday, November 14, 2021 9:17:48 PM CST',
        'Friday, November 12, 2021 2:12:31 PM CST',
        'Wednesday, November 10, 2021 1:19:40 PM CST',
        'Friday, November 5, 2021 3:50:51 PM CST',
        'Wednesday, November 3, 2021 1:08:25 PM CST',
        'Monday, November 1, 2021 3:11:59 PM CST',
        'Friday, October 29, 2021 1:25:24 PM CST',
        'Wednesday, October 27, 2021 1:01:57 PM CST',
        'Wednesday, October 20, 2021 1:18:02 PM CST',
        'Friday, October 15, 2021 1:19:08 PM CST',
        'Wednesday, October 13, 2021 1:18:19 PM CST',
        'Saturday, October 9, 2021 12:51:21 PM CST',
        'Friday, October 8, 2021 1:24:07 PM CST',
        'Saturday, October 2, 2021 12:35:43 PM CST',
        'Thursday, September 30, 2021 7:15:03 PM CST',
        'Wednesday, September 29, 2021 12:02:48 PM CST',
        'Tuesday, September 28, 2021 10:29:48 AM CST',
        'Monday, September 27, 2021 8:12:55 AM CST',
        'Sunday, September 26, 2021 8:10:40 AM CST',
        'Friday, September 24, 2021 12:02:28 PM CST',
        'Wednesday, September 22, 2021 12:10:37 PM CST',
        'Friday, September 17, 2021 12:53:49 PM CST',
        'Thursday, September 16, 2021 3:57:38 PM CST',
        'Wednesday, September 15, 2021 4:44:11 PM CST',
        'Wednesday, September 15, 2021 12:32:41 PM CST',
        'Tuesday, September 14, 2021 8:00:46 PM CST',
        'Sunday, September 5, 2021 11:10:27 AM CST',
        'Sunday, September 5, 2021 11:05:04 AM CST',
        'Tuesday, September 21, 2021 9:13:48 AM CST',
        'Monday, September 13, 2021 9:03:50 PM CST',
        'Friday, April 9, 2021 12:30:00 PM CST',
        'Saturday, May 16, 2020 12:25:10 PM CST',
        'Monday, April 13, 2020 2:25:53 AM CST',
        'Wednesday, March 11, 2020 4:31:57 AM CST',
        'Monday, February 17, 2020 5:31:15 PM CST',
        'Monday, February 17, 2020 4:40:31 PM CST',
        'Sunday, February 16, 2020 3:05:35 PM CST',
        'Tuesday, April 6, 2021 10:03:46 AM CST',
        'Saturday, May 8, 2021 8:58:22 AM CST',
        'Sunday, April 25, 2021 5:40:47 PM CST',
        'Sunday, April 25, 2021 5:41:38 PM CST',
        'Thursday, April 15, 2021 5:21:52 PM CST',
        'Thursday, April 8, 2021 3:29:06 PM CST',
        'Thursday, April 1, 2021 5:50:10 PM CST',
        'Friday, March 26, 2021 2:44:27 PM CST',
        'Friday, January 15, 2021 2:56:12 PM CST',
        'Friday, January 15, 2021 11:18:29 AM CST',
        'Wednesday, May 12, 2021 7:50:41 PM CST',
        'Sunday, April 18, 2021 9:00:10 PM CST',
        'Friday, April 2, 2021 2:17:11 PM CST',
        'Monday, March 29, 2021 3:17:18 PM CST',
        'Thursday, March 18, 2021 10:49:04 AM CST',
        'Friday, March 12, 2021 11:11:57 AM CST',
        'Friday, March 5, 2021 11:46:51 AM CST',
        'Monday, January 11, 2021 5:48:14 PM CST',
        'Tuesday, April 13, 2021 10:12:10 PM CST',
        'Wednesday, January 20, 2021 11:29:02 AM CST',
        'Wednesday, January 13, 2021 9:08:45 PM CST',
        'Wednesday, January 13, 2021 11:14:51 AM CST',
        'Thursday, March 31, 2022 5:12:58 PM CST',
        'Tuesday, February 25, 2020 9:20:21 AM CST'
    ],
    'Posted By': [
        '陈浩哲 (Chen Haozhe) ZJU-UIUC Institute',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Mark D. Butala 国际联合学院(海宁国际校区)',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Klaus-Dieter Schewe ZJU-UIUC Institute',
        'Zuofu UIUC',
        '李楚杉 ZJU-UIUC Institute',
        '林妙蓉 社会学',
        'Robert Holmes Liberal Arts&Science college',
        'William Denny 浙江大学国际联合学院',
        'William Denny 浙江大学国际联合学院',
        'William Denny 浙江大学国际联合学院',
        'William Denny 浙江大学国际联合学院',
        'Robert Holmes Liberal Arts&Science college',
        '夏焕新 国际联合学院(海宁国际校区)',
        'Oleksiy Penkov ZJU-UIUC Institute',
        'Oleksiy Penkov ZJU-UIUC Institute',
        'Oleksiy Penkov ZJU-UIUC Institute',
        'Oleksiy Penkov ZJU-UIUC Institute',
        'Oleksiy Penkov ZJU-UIUC Institute',
        'Oleksiy Penkov ZJU-UIUC Institute',
        'Oleksiy Penkov ZJU-UIUC Institute',
        '夏焕新 国际联合学院(海宁国际校区)',
        '夏焕新 国际联合学院(海宁国际校区)',
        '陈文超 国际联合学院(海宁国际校区)',
        '陈文超 国际联合学院(海宁国际校区)',
        '陈文超 国际联合学院(海宁国际校区)',
        '陈文超 国际联合学院(海宁国际校区)',
        '陈文超 国际联合学院(海宁国际校区)',
        '陈文超 国际联合学院(海宁国际校区)',
        '陈文超 国际联合学院(海宁国际校区)',
        '陈文超 国际联合学院(海宁国际校区)',
        '许欢 (Xu Huan) ZJU-UIUC Institute',
        '陈文超 国际联合学院(海宁国际校区)',
        '许欢 (Xu Huan) ZJU-UIUC Institute',
        '陈文超 国际联合学院(海宁国际校区)',
        '王玉芬 (WANGYUFEN) ZJU',
        '谢佳妮 后勤集团'
    ],
    'Posted To': [
        'ECE220: Computer Systems & Programming (Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE313:Probability with Engineering Application-1132(Fall 2021)',
        'ECE314:Probability with Engineering Application Lab-1133-1134-1135-1136-LAB(Fall 2021)',
        'ECE314:Probability with Engineering Application Lab-1133-1134-1135-1136-LAB(Fall 2021)',
        'ECE314:Probability with Engineering Application Lab-1133-1134-1135-1136-LAB(Fall 2021)',
        'ECE314:Probability with Engineering Application Lab-1133-1134-1135-1136-LAB(Fall 2021)',
        'ECE314:Probability with Engineering Application Lab-1133-1134-1135-1136-LAB(Fall 2021)',
        'ECE314:Probability with Engineering Application Lab-1133-1134-1135-1136-LAB(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE374:Introduction to Algorithms&& Models of Computation-1125(Fall 2021)',
        'ECE385:Digital Systems Laboratory-1130(Fall 2021)',
        'ECE385:Digital Systems Laboratory-1130(Fall 2021)',
        'GCL200:FrameworksforInequality-LEC-1518(20-21)',
        'Integrated English Ⅱ',
        'Integrated English Ⅱ',
        'Integrated English Ⅱ',
        'Integrated English Ⅱ',
        'Integrated English Ⅱ',
        'Integrated English Ⅱ',
        'PHYS213:Univ PhysicsThermal Physics-Lab',
        'PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)',
        'PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)',
        'PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)',
        'PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)',
        'PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)',
        'PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)',
        'PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)',
        'PHYS214:Univ Physics-Quantum Physics',
        'PHYS214:Univ Physics-Quantum Physics',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)',
        'PS2001D:Situation and Policy Ⅱ-1500-PRA-2120',
        'Residential College'
    ],
    'Stipulate': [
        'Please vote for TAs' office hour on Campuswire. ',
        'The final in-class activity will be this Thursday. It will be administered remotely. The topic will be on binary hypothesis testing. We will not have a homework on this topic (there will be no further homeworks this semester).\n',
        'Dear students,\nPlease find the QR code to access the course evaluation form for ECE 313 below. Please take the time to complete the evaluation and make your voice heard. I take the course evaluations very seriously: the numeric scores provide general impressions and I also read every student comment. This is important information for me to aid my planning and course execution in the future.\n',
        'You are allowed three sheets of notes (A4 paper, you can use both sides)\nThe exam is comprehensive\nMaterial since exam 2, as it has not appeared yet on an exam, will receive some emphasis.\n',
        'Scores and feedback have been posted.\nFor reference, the score distribution for Exam 2 is as follows.\n',
        'Prof. Iyer will be providing lectures for the last week of class. We will continue with online teaching for the rest of the semester. The login information is the same as before:\nTopic: ECE 313 lecture\nTime: Dec 20, 2021 11:00 AM Beijing, Shanghai\nJoin Zoom Meeting\nhttps://illinois.zoom.us/j/7322892292?pwd=dlIwTm53NG00QlMrbFJlSWR6dzZnUT09\nMeeting ID: 732 289 2292\nPassword: 388403\n',
        'Here are announcements concerning the exam:\nThe exam is tonight, December 14th, from 19:00 to 21:00. Please log in to your section early so that you do not miss the start of the exam.\nPlease refer to the announcement below for which online proctor section you have been assigned to.\nYou must have your camera on during the exam.\nThe exam is open book and notes.\nYou are not allowed to use any calculators, phones, or any electronic devices during the exam (you may use a tablet or similar device if you want to submit an electronic version of your solution).\nYou are on your honor. No communication with other students is permitted.\nWhen you have completed the exam and before 21:00, upload a scanned, photographed, or electronic version of your solution to the \'Exam 2\' assignment on Blackboard.\n',
        'Group 1: https://illinois.zoom.us/j/7322892292?pwd=dlIwTm53NG00QlMrbFJlSWR6dzZnUT09\n|         ID | Name                  |\n|-----------:|:----------------------|\n| 3160103194 | 金仁杰 (Jin Renjie)   |\n| 3190110008 | 刘子昂 (Liu Ziang)    |\n| 3190110095 | 赵傲 (Zhao Ao)        |\n| 3190110098 | 李子豪 (Li Zihao)     |\n| 3190110099 | 宋一非 (Song Yifei)   |\n| 3190110227 | 张博昊 (Zhang Bohao)  |\n| 3190110311 | 罗家宜 (Luo Jiayi)    |\n| 3190110313 | 安梓阳 (An Ziyang)    |\n| 3190110352 | 朱晓涵 (Zhu Xiaohan)  |\n| 3190110354 | 周阳 (Zhou Yang)      |\n| 3190110360 | 许可 (Xu Ke)          |\n| 3190110361 | 朱康榆 (Zhu Kangyu)   |\n| 3190110362 | 姜大磊 (Jiang Dalei)  |\n| 3190110384 | 杨涵 (Yang Han)       |\n| 3190110385 | 李辰浩 (Li Chenhao)   |\n| 3190110414 | 屈雨欣 (Qu Yuxin)     |\n| 3190110572 | 楼海纳 (Lou Haina)    |\n| 3190110665 | 刘瀚文 (Liu Hanwen)   |\n| 3190110667 | 陈世昕 (Chen Shixin)  |\n| 3190110670 | 柳滢颖 (Liu Yingying) |\n| 3190110710 | 宋博文 (Song Bowen)   |\n| 3190110711 | 金星语 (Jin Xingyu)   |\n| 3190110717 | 仇晓敏 (Qiu Xiaomin)  |\n| 3190110719 | 钱立杨 (Qian Liyang)  |\n| 3190110720 | 姜宇轩 (Jiang Yuxuan) |\n| 3190110721 | 柳畅 (Liu Chang)      |\n| 3190110785 | 方博洋 (Fang Boyang)  |\n| 3190110786 | 翁天乐 (Weng Tianle)  |\n| 3190110787 | 王子文 (Wang Ziwen)   |\n| 3190110844 | 郭易详 (Guo Yixiang)  |\n| 3190110845 | 袁晨泰 (Yuan Chentai) |\n| 3190110853 | 陈赫 (Chen He)        |\n| 3190110909 | 谢飞帆 (Xie Feifan)   |\n| 3190110910 | 王家捷 (Wang Jiajie)  |\n| 3190112150 | 黎堃乐 (Li Kunle)     |\n| 3190112154 | 王昊旻 (Wang Haomin)  |\n| 3190112155 | 漆振霆 (Qi Zhenting)  |\n| 3190114710 | 司振左 (Si Zhenzuo)   |\nGroup 2: https://illinois.zoom.us/j/2228030836?pwd=cUdwMGZvejlOOXlwMzAyVHpCSkpMdz09\n|         ID | Name                    |\n|-----------:|:------------------------|\n| 3170111407 | 张琰 (Zhang Yan)        |\n| 3190110006 | 杭哲义 (Hang Zheyi)     |\n| 3190110093 | 杜天泽 (Du Tianze)      |\n| 3190110097 | 李浩博 (Li Haobo)       |\n| 3190110302 | 董傲 (Dong Ao)          |\n| 3190110306 | 孔子泰 (Kong Zitai)     |\n| 3190110308 | 贺宝仪 (He Baoyi)       |\n| 3190110314 | 杨帆 (Yang Fan)         |\n| 3190110349 | 沈鲁一 (Shen Luyi)      |\n| 3190110353 | 张亦弛 (Zhang Yichi)    |\n| 3190110381 | 周以轲 (Zhou Yike)      |\n| 3190110389 | 周修远 (Zhou Xiuyuan)   |\n| 3190110390 | 陆珂宇 (Lu Keyu)        |\n| 3190110391 | 徐鉴波 (Xu Jianbo)      |\n| 3190110392 | 李天乐 (Li Tianle)      |\n| 3190110393 | 周俊丞 (Zhou Juncheng)  |\n| 3190110394 | 徐凯杰 (Xu Kaijie)      |\n| 3190110672 | 邱浩宇 (Qiu Haoyu)      |\n| 3190110675 | 赵图南 (Zhao Tunan)     |\n| 3190110714 | 白昊 (Bai Hao)          |\n| 3190110715 | 金亦宏 (Jin Yihong)     |\n| 3190110716 | 姚文韬 (Yao Wentao)     |\n| 3190110782 | 吕天成 (Lv Tiancheng)   |\n| 3190110788 | 谢沐 (Xie Mu)           |\n| 3190110842 | 张有成 (Zhang Youcheng) |\n| 3190110843 | 王和月 (Wang Heyue)     |\n| 3190110855 | 于天骐 (Yu Tianqi)      |\n| 3190110906 | 郁涵玮 (Yu Hanwei)      |\n| 3190110908 | 李奕辉 (Li Yihui)       |\n| 3190110911 | 丁浩 (Ding Hao)         |\n| 3190110913 | 章灵杰 (Zhang Lingjie)  |\n| 3190110914 | 柯汝成 (Ke Rucheng)     |\n| 3190110915 | 张雨秋 (Zhang Yuqiu)    |\n| 3190112145 | 林佳铠 (Lin Jiakai)     |\n| 3190112146 | 王定坤 (Wang Dingkun)   |\n| 3190112148 | 周琦深 (Zhou Qishen)    |\n| 3190112157 | 贺一航 (He Yihang)      |\n| 3190112160 | 张凯 (Zhang Kai)        |\nGroup 3: dingtalk://dingtalkclient/page/videoConfFromCalendar?confId=7faf029c-9f1c-4081-b795-e55d77adee55&calendarId=1478221615\n|         ID | Name                    |\n|-----------:|:------------------------|\n| 3180111646 | 王致渊 (Wang Zhiyuan)   |\n| 3190110094 | 金凯隆 (Jin Kailong)    |\n| 3190110269 | 昌隆 (Chang Long)       |\n| 3190110303 | 王潇 (Wang Xiao)        |\n| 3190110312 | 苏畅 (Su Chang)         |\n| 3190110316 | 郭漠杨 (Guo Moyang)     |\n| 3190110355 | 傅哲宇 (Fu Zheyu)       |\n| 3190110356 | 张佳宇 (Zhang Jiayu)    |\n| 3190110357 | 谢致远 (Xie Zhiyuan)    |\n| 3190110358 | 戚哲昊 (Qi Zhehao)      |\n| 3190110382 | 华秉晟 (Hua Bingsheng)  |\n| 3190110383 | 胡家润 (Hu Jiarun)      |\n| 3190110386 | 沈珂伊 (Shen Keyi)      |\n| 3190110387 | 夏杰邦 (Xia Jiebang)    |\n| 3190110388 | 钱帅存 (Qian Shuaicun)  |\n| 3190110395 | 叶政朴 (Ye Zhengpu)     |\n| 3190110396 | 刘京诚 (Liu Jingcheng)  |\n| 3190110512 | 肖子昱 (Xiao Ziyu)      |\n| 3190110669 | 庞博 (Pang Bo)          |\n| 3190110674 | 葛昱昊 (Ge Yuhao)       |\n| 3190110712 | 林子渊 (Lin Ziyuan)     |\n| 3190110713 | 何詹昊 (He Zhanhao)     |\n| 3190110783 | 郭舒涵 (Guo Shuhan)     |\n| 3190110784 | 陈钱中 (Chen Qianzhong) |\n| 3190110789 | 严瑞轲 (Yan Ruike)      |\n| 3190110839 | 徐远 (Xu Yuan)          |\n| 3190110846 | 夏新宇 (Xia Xinyu)      |\n| 3190110847 | 龚言昭 (Gong Yanzhao)   |\n| 3190110848 | 倪文韬 (Ni Wentao)      |\n| 3190110849 | 沈战宇 (Shen Zhanyu)    |\n| 3190110851 | 施奕辰 (Shi Yichen)     |\n| 3190110907 | 滕智博 (Teng Zhibo)     |\n| 3190112149 | 陈昊 (Chen Hao)         |\n| 3190112152 | 陈亭桦 (Chen Tinghua)   |\n| 3190112153 | 邱越 (Qiu Yue)          |\n| 3190112158 | 刘培源 (Liu Peiyuan)    |\n| 3190114831 | 陈诗宇 (Chen Shiyu)     |\n| 3190115806 | 谭凯元 (Tan Kaiyuan)    |\nGroup 4: https://illinois.zoom.us/j/4803217506?pwd=VE94R0ZXVUp2ZWJ4Mm9oTW1NTUswZz09\n|         ID | Name                     |\n|-----------:|:-------------------------|\n| 3170110159 | 薛童 (Xue Tong)          |\n| 3180111641 | 潘毅略 (Pan Yilue)       |\n| 3190110005 | 金亦柔 (Jin Yirou)       |\n| 3190110007 | 李博言 (Li Boyan)        |\n| 3190110010 | 朱欣文 (Zhu Xinwen)      |\n| 3190110096 | 贾哲洋 (Jia Zheyang)     |\n| 3190110100 | 李康宁 (Li Kangning)     |\n| 3190110101 | 徐家真 (Xu Jiazhen)      |\n| 3190110102 | 张曦冉 (Zhang Xiran)     |\n| 3190110304 | 韩子飞 (Han Zifei)       |\n| 3190110305 | 张天宇 (Zhang Tianyu)    |\n| 3190110307 | 吴小山 (Wu Xiaoshan)     |\n| 3190110309 | 王鑫 (Wang Xin)          |\n| 3190110310 | 李伯闻 (Li Bowen)        |\n| 3190110315 | 李金珂 (Li Jinke)        |\n| 3190110348 | 金轶驰 (Jin Yichi)       |\n| 3190110350 | 邵淑婷 (Shao Shuting)    |\n| 3190110359 | 应安禹 (Ying Anyu)       |\n| 3190110363 | 王永灿 (Wang Yongcan)    |\n| 3190110380 | 童霖杰 (Tong Linjie)     |\n| 3190110413 | 朱宇涛 (Zhu Yutao)       |\n| 3190110666 | 傅关抒杰 (Fu Guanshujie) |\n| 3190110668 | 叶睿祺 (Ye Ruiqi)        |\n| 3190110671 | 吴中祺 (Wu Zhongqi)      |\n| 3190110709 | 陈清扬 (Chen Qingyang)   |\n| 3190110718 | 吴若晨 (Wu Ruochen)      |\n| 3190110722 | 方正 (Fang Zheng)        |\n| 3190110840 | 俞辰晨 (Yu Chenchen)     |\n| 3190110841 | 姚沛衡 (Yao Peiheng)     |\n| 3190110850 | 叶崭伦 (Ye Zhanlun)      |\n| 3190110852 | 袁陈智 (Yuan Chenzhi)    |\n| 3190110854 | 刘彭钊 (Liu Pengzhao)    |\n| 3190110912 | 钱书仰 (Qian Shuyang)    |\n| 3190112142 | 刘煜 (Liu Yu)            |\n| 3190112144 | 魏嘉豪 (Wei Jiahao)      |\n| 3190112147 | 李俊彦 (Li Junyan)       |\n| 3190112151 | 胡楚瑄 (Hu Chuxuan)      |\n| 3190112156 | 陈炫宇 (Chen Xuanyu)     |\n',
        'You may use whatever textbooks or notes you would like for exam 2.\n',
        'Exam 2 will focus on the following (inclusive):\nLectures 19 through 32\nRoss textbook Chapter 6, 7\nHajek notes Section 2.8, 2.9, 3.7, 3.8, 4.1 - 4.8\n',
        'Online lectures will continue this week. The link is the same as before: https://illinois.zoom.us/j/7322892292?pwd=dlIwTm53NG00QlMrbFJlSWR6dzZnUT09\n',
        'As you have probably heard by now, remote teaching will continue today. Here are some related announcements:\nPlease join lecture by zoom at the same link as before (https://illinois.zoom.us/j/7322892292?pwd=dlIwTm53NG00QlMrbFJlSWR6dzZnUT09)\nWe will have the in-class activity today. I will post it as an assignment. Please download the in-class activity .pdf, work with a small team, and submit your solution (scanned/photograph or electronic) to Blackboard by the deadline.\n',
        'As you may have already heard, in-person teaching will not resume until Thursday, December 9th. Consequently:\nExam 2 has been postponed until Tuesday, December 14th. The scope and coverage of exam 2 remains unchanged, i.e., there are no changes regrading exam 2 except the date of the exam.\nLecture on Monday, December 6 and Tuesday, December 7 will be held on Zoom (same as this week).\nLecture is canceled on Tuesday, December 14th.\nIn-class activity #6 will be on Thursday, December 9th.\n',
        'We covered these topics only just this week, but they are important metrics for characterizing joint distributions. I would say the probability is high that exam 2 may ask questions concerning correlation, covariance, and/or correlation coefficient.\n',
        'You may bring two A4 sheets of notes to Exam 2. You can write on both sides. \n',
        'Lecture is canceled on Tuesday, December 7th because we are having an exam on the same date.\n',
        'Teaching will be online this week. Please join lecture at the following link:\nJoin Zoom Meetinghttps://illinois.zoom.us/j/7322892292?pwd=dlIwTm53NG00QlMrbFJlSWR6dzZnUT09\nMeeting ID: 732 289 2292\nPassword: 388403\n',
        'The teaching staff will be available in the library coffee shop from 12:30 to 13:30 Friday, Nov. 19th to address marking questions for Exam 1.\n',
        'There will not be a homework assignment this week.\n',
        'Starting Monday, November 15th, class will meet in  Lecture Theater West room LTW102.\n',
        'Teaching Building A room 414/416:\n|         ID | Name                    |\n|-----------:|:------------------------|\n| 3160103194 | 金仁杰 (Jin Renjie)     |\n| 3170110159 | 薛童 (Xue Tong)         |\n| 3170111407 | 张琰 (Zhang Yan)        |\n| 3180111556 | 应凯众 (Ying Kaizhong)  |\n| 3180111641 | 潘毅略 (Pan Yilue)      |\n| 3180111646 | 王致渊 (Wang Zhiyuan)   |\n| 3190110005 | 金亦柔 (Jin Yirou)      |\n| 3190110007 | 李博言 (Li Boyan)       |\n| 3190110094 | 金凯隆 (Jin Kailong)    |\n| 3190110097 | 李浩博 (Li Haobo)       |\n| 3190110098 | 李子豪 (Li Zihao)       |\n| 3190110099 | 宋一非 (Song Yifei)     |\n| 3190110100 | 李康宁 (Li Kangning)    |\n| 3190110101 | 徐家真 (Xu Jiazhen)     |\n| 3190110102 | 张曦冉 (Zhang Xiran)    |\n| 3190110307 | 吴小山 (Wu Xiaoshan)    |\n| 3190110310 | 李伯闻 (Li Bowen)       |\n| 3190110312 | 苏畅 (Su Chang)         |\n| 3190110316 | 郭漠杨 (Guo Moyang)     |\n| 3190110349 | 沈鲁一 (Shen Luyi)      |\n| 3190110352 | 朱晓涵 (Zhu Xiaohan)    |\n| 3190110354 | 周阳 (Zhou Yang)        |\n| 3190110355 | 傅哲宇 (Fu Zheyu)       |\n| 3190110356 | 张佳宇 (Zhang Jiayu)    |\n| 3190110359 | 应安禹 (Ying Anyu)      |\n| 3190110360 | 许可 (Xu Ke)            |\n| 3190110362 | 姜大磊 (Jiang Dalei)    |\n| 3190110380 | 童霖杰 (Tong Linjie)    |\n| 3190110385 | 李辰浩 (Li Chenhao)     |\n| 3190110386 | 沈珂伊 (Shen Keyi)      |\n| 3190110390 | 陆珂宇 (Lu Keyu)        |\n| 3190110391 | 徐鉴波 (Xu Jianbo)      |\n| 3190110392 | 李天乐 (Li Tianle)      |\n| 3190110393 | 周俊丞 (Zhou Juncheng)  |\n| 3190110413 | 朱宇涛 (Zhu Yutao)      |\n| 3190110512 | 肖子昱 (Xiao Ziyu)      |\n| 3190110572 | 楼海纳 (Lou Haina)      |\n| 3190110667 | 陈世昕 (Chen Shixin)    |\n| 3190110669 | 庞博 (Pang Bo)          |\n| 3190110670 | 柳滢颖 (Liu Yingying)   |\n| 3190110672 | 邱浩宇 (Qiu Haoyu)      |\n| 3190110711 | 金星语 (Jin Xingyu)     |\n| 3190110712 | 林子渊 (Lin Ziyuan)     |\n| 3190110715 | 金亦宏 (Jin Yihong)     |\n| 3190110716 | 姚文韬 (Yao Wentao)     |\n| 3190110717 | 仇晓敏 (Qiu Xiaomin)    |\n| 3190110719 | 钱立杨 (Qian Liyang)    |\n| 3190110721 | 柳畅 (Liu Chang)        |\n| 3190110785 | 方博洋 (Fang Boyang)    |\n| 3190110786 | 翁天乐 (Weng Tianle)    |\n| 3190110787 | 王子文 (Wang Ziwen)     |\n| 3190110840 | 俞辰晨 (Yu Chenchen)    |\n| 3190110841 | 姚沛衡 (Yao Peiheng)    |\n| 3190110842 | 张有成 (Zhang Youcheng) |\n| 3190110844 | 郭易详 (Guo Yixiang)    |\n| 3190110849 | 沈战宇 (Shen Zhanyu)    |\n| 3190110850 | 叶崭伦 (Ye Zhanlun)     |\n| 3190110852 | 袁陈智 (Yuan Chenzhi)   |\n| 3190110854 | 刘彭钊 (Liu Pengzhao)   |\n| 3190110906 | 郁涵玮 (Yu Hanwei)      |\n| 3190110910 | 王家捷 (Wang Jiajie)    |\n| 3190110913 | 章灵杰 (Zhang Lingjie)  |\n| 3190110914 | 柯汝成 (Ke Rucheng)     |\n| 3190110915 | 张雨秋 (Zhang Yuqiu)    |\n| 3190112145 | 林佳铠 (Lin Jiakai)     |\n| 3190112147 | 李俊彦 (Li Junyan)      |\n| 3190112149 | 陈昊 (Chen Hao)         |\n| 3190112151 | 胡楚瑄 (Hu Chuxuan)     |\n| 3190112152 | 陈亭桦 (Chen Tinghua)   |\n| 3190112153 | 邱越 (Qiu Yue)          |\n| 3190112154 | 王昊旻 (Wang Haomin)    |\n| 3190112155 | 漆振霆 (Qi Zhenting)    |\n| 3190112157 | 贺一航 (He Yihang)      |\n| 3190112160 | 张凯 (Zhang Kai)        |\n| 3190114710 | 司振左 (Si Zhenzuo)     |\n| 3190114831 | 陈诗宇 (Chen Shiyu)     |\nTeaching Building A room 418/420:\n|         ID | Name                     |\n|-----------:|:-------------------------|\n| 3190110006 | 杭哲义 (Hang Zheyi)      |\n| 3190110008 | 刘子昂 (Liu Ziang)       |\n| 3190110010 | 朱欣文 (Zhu Xinwen)      |\n| 3190110093 | 杜天泽 (Du Tianze)       |\n| 3190110095 | 赵傲 (Zhao Ao)           |\n| 3190110096 | 贾哲洋 (Jia Zheyang)     |\n| 3190110227 | 张博昊 (Zhang Bohao)     |\n| 3190110269 | 昌隆 (Chang Long)        |\n| 3190110302 | 董傲 (Dong Ao)           |\n| 3190110303 | 王潇 (Wang Xiao)         |\n| 3190110304 | 韩子飞 (Han Zifei)       |\n| 3190110305 | 张天宇 (Zhang Tianyu)    |\n| 3190110306 | 孔子泰 (Kong Zitai)      |\n| 3190110308 | 贺宝仪 (He Baoyi)        |\n| 3190110309 | 王鑫 (Wang Xin)          |\n| 3190110311 | 罗家宜 (Luo Jiayi)       |\n| 3190110313 | 安梓阳 (An Ziyang)       |\n| 3190110314 | 杨帆 (Yang Fan)          |\n| 3190110315 | 李金珂 (Li Jinke)        |\n| 3190110348 | 金轶驰 (Jin Yichi)       |\n| 3190110350 | 邵淑婷 (Shao Shuting)    |\n| 3190110353 | 张亦弛 (Zhang Yichi)     |\n| 3190110357 | 谢致远 (Xie Zhiyuan)     |\n| 3190110358 | 戚哲昊 (Qi Zhehao)       |\n| 3190110361 | 朱康榆 (Zhu Kangyu)      |\n| 3190110363 | 王永灿 (Wang Yongcan)    |\n| 3190110381 | 周以轲 (Zhou Yike)       |\n| 3190110382 | 华秉晟 (Hua Bingsheng)   |\n| 3190110383 | 胡家润 (Hu Jiarun)       |\n| 3190110384 | 杨涵 (Yang Han)          |\n| 3190110387 | 夏杰邦 (Xia Jiebang)     |\n| 3190110388 | 钱帅存 (Qian Shuaicun)   |\n| 3190110389 | 周修远 (Zhou Xiuyuan)    |\n| 3190110394 | 徐凯杰 (Xu Kaijie)       |\n| 3190110395 | 叶政朴 (Ye Zhengpu)      |\n| 3190110396 | 刘京诚 (Liu Jingcheng)   |\n| 3190110414 | 屈雨欣 (Qu Yuxin)        |\n| 3190110665 | 刘瀚文 (Liu Hanwen)      |\n| 3190110666 | 傅关抒杰 (Fu Guanshujie) |\n| 3190110668 | 叶睿祺 (Ye Ruiqi)        |\n| 3190110671 | 吴中祺 (Wu Zhongqi)      |\n| 3190110674 | 葛昱昊 (Ge Yuhao)        |\n| 3190110675 | 赵图南 (Zhao Tunan)      |\n| 3190110709 | 陈清扬 (Chen Qingyang)   |\n| 3190110710 | 宋博文 (Song Bowen)      |\n| 3190110713 | 何詹昊 (He Zhanhao)      |\n| 3190110714 | 白昊 (Bai Hao)           |\n| 3190110718 | 吴若晨 (Wu Ruochen)      |\n| 3190110720 | 姜宇轩 (Jiang Yuxuan)    |\n| 3190110722 | 方正 (Fang Zheng)        |\n| 3190110782 | 吕天成 (Lv Tiancheng)    |\n| 3190110783 | 郭舒涵 (Guo Shuhan)      |\n| 3190110784 | 陈钱中 (Chen Qianzhong)  |\n| 3190110788 | 谢沐 (Xie Mu)            |\n| 3190110789 | 严瑞轲 (Yan Ruike)       |\n| 3190110839 | 徐远 (Xu Yuan)           |\n| 3190110843 | 王和月 (Wang Heyue)      |\n| 3190110845 | 袁晨泰 (Yuan Chentai)    |\n| 3190110846 | 夏新宇 (Xia Xinyu)       |\n| 3190110847 | 龚言昭 (Gong Yanzhao)    |\n| 3190110848 | 倪文韬 (Ni Wentao)       |\n| 3190110851 | 施奕辰 (Shi Yichen)      |\n| 3190110853 | 陈赫 (Chen He)           |\n| 3190110855 | 于天骐 (Yu Tianqi)       |\n| 3190110907 | 滕智博 (Teng Zhibo)      |\n| 3190110908 | 李奕辉 (Li Yihui)        |\n| 3190110909 | 谢飞帆 (Xie Feifan)      |\n| 3190110911 | 丁浩 (Ding Hao)          |\n| 3190110912 | 钱书仰 (Qian Shuyang)    |\n| 3190112142 | 刘煜 (Liu Yu)            |\n| 3190112144 | 魏嘉豪 (Wei Jiahao)      |\n| 3190112146 | 王定坤 (Wang Dingkun)    |\n| 3190112148 | 周琦深 (Zhou Qishen)     |\n| 3190112150 | 黎堃乐 (Li Kunle)        |\n| 3190112156 | 陈炫宇 (Chen Xuanyu)     |\n| 3190112158 | 刘培源 (Liu Peiyuan)     |\n| 3190115806 | 谭凯元 (Tan Kaiyuan)     |\n',
        'There will be no lecture on Monday.\n',
        'To give extra time to study for the exam, there will be no homework this week.\n',
        'Bruce Hajek's notes are listed as a companion textbook for the course. They are freely available here: https://hajek.ece.illinois.edu/ECE313Notes.html\nThe following sections (incusive) are encompassed by the scope of exam 1:\nSections 1.1 - 1.4\nSections 2.1 - 2.7, 2.10, 2.12\nSections 3.1 - 3.6, 3.9\n',
        'The ZJUI academic staff have confirmed with me that Tuesday evening is open for everyone. This time slot avoids other conflicts.\nFurther details (location) will be announced.\nExam scope: all lecture material up to and including the lecture on Thursday, Oct. 28th and chapters 1-5 + section 9.1 from the Ross textbook.\nYou are allowed to bring one A4 sheet of paper of notes to the exam.\nPast ECE 313 exams can be found here: https://courses.engr.illinois.edu/ece313/fa2021/old_exams.html\n',
        'I have confirmed with the ZJUI academic staff that Friday evenings are open for everyone in class.\nFurther details will be announced.\nExam scope: all lecture material up to and including the lecture on Thursday, Oct. 28th and chapters 1-5 from the Ross textbook.\nPast ECE 313 exams can be found here: https://courses.engr.illinois.edu/ece313/fa2021/old_exams.html\n',
        'Further details, e.g., location, will follow.\nExam scope: all lecture material up to and including the lecture on Thursday, Oct. 28th and chapters 1-5 from the Ross textbook.\nPast ECE 313 exams can be found here: https://courses.engr.illinois.edu/ece313/fa2021/old_exams.html\n',
        'The PPT lecture notes sometimes use animations. The previous PDF export did not take this into consideration. I have updated the uploaded lecture notes to show the slides after animations are complete. \nI will do my best to remember to do this in the future. If I forget, let me know and I will reupload.\nCourse Link/Weekly Progress/Lecture notes\n',
        'Please find it at the link associated with this post.\nThe WeChat group is NOT meant to replace the Piazza Q&A forum. Use the WeChat group to communicate directly with the TAs.\nCourse Link/Getting Started/QR code for course WeChat group\n',
        'Lecture notes will be posted at the located linked to in this announcement.\nCourse Link/Weekly Progress/Lecture notes\n',
        'We will use Piazza to manage a forum-based discussion for ECE 313/314. Please join the discussion site here: https://piazza.com/zju.edu.cn/fall2021/ece313314\n',
        'Please find the course syllabus at the indicated location.\nCourse Link/Getting Started/Course syllabus\n',
        'Dear students,\nPlease find the QR code to access the course evaluation form for ECE 314 below. Please take the time to complete the evaluation and make your voice heard. I take the course evaluations very seriously: the numeric scores provide general impressions and I also read every student comment. This is important information for me to aid my planning and course execution in the future.\n',
        'A student brought an issue to my attention: the original version of Lab 1 included a warning regarding the version of Python to use. I had inadvertently uploaded an old version of Lab 1. Please use the updated version which is compatible with Python 3 and complete this and future lab assignments using Python 3.\nCourse Link/Weekly Progress/Lab 1\n',
        'As stated in the course syllabus, attendance at lab is not required. Please do not hesitate to contact the instructor or a TA is you need any assistance with a lab.\nHowever, if you would like to use the computer lab (E1-E4) then please contact me and I will make sure you are granted access.\n',
        'If you are unfamiliar with Python or need a refresher, please refer to Lab 0. It is provided for you benefit, you do not have to submit a solution, and no credit is given for lab 0.\nCourse Link/Getting Started/Lab 0\n',
        'Please note that an updated version has been posted adjusting the lab due dates to Wednesdays.\nCourse Link/Getting Started/Course syllabus\n',
        'Please find the course syllabus posted at the indicated location.\nCourse Link/Getting Started/Course syllabus\n',
        'The final exam has been graded. Finally, 60 pts. were counted as 100%. The weighted average of homework (55%), midterm (15%) and final exam (30%) has been calculated. Cutoff points between grades have been slightly adjusted.\nYou will find all scores in BB. If there is any serious mistake, please let us know before 10am tomorrow morning. After this time the grades will be uploaded, and cannot be changed anymore.\n',
        'The model answers for Assignment 12 will be released tomorrow morning, Dec. 27, at 10am. Please keep in mind that no late submission of the assignment can be accepted, if it is later than the release of the model answers.\n',
        'The last lecture slot for this semester on this Friday, December 24, is dedicated to a revision. If you have questions what you would like to revise again, please send them to me.\nThere will be no zoom session for the revision and no video recording. We will mainly use the whiteboards.\n',
        'A video of today's lecture will be soon available at\nhttps://media.intl.zju.edu.cn/Media/Play/467d1a2c5b674e5a8348ffeca8c055a51d\nIt is the last video recording for this semester.\n',
        'Note that a hint has been added to Assignment 12.\n',
        'The following link will take you to the course feedback form. We appreciate if you could complete this survey by Dec. 26.\nhttps://forms.office.com/Pages/ResponsePage.aspx?id=xSAmKRCuU0Wsz2jsgDJQCOyRCXXAbFdNl4Oej4tC0c1UNURVVEoyTktDOFRCMFVKTUQ3Uzg3TTlURC4u\nUnder \'course content\' you will also find a QR code which you can scan in WeChat to access the course feedback form.\n',
        'Due to some mistake, Ex.4 in Ass.11 has been reduced.\n',
        'Teaching this week , Dec. 20-24, will be resumed in the classrooms.\n',
        'A video of today's lecture will soon become available at\nhttps://media.intl.zju.edu.cn/Media/Play/57e90a2bd5f84c419f9b5d5d93a7c4eb1d\n',
        'The final exam is scheduled for December 28, 9:00-12:00 in LTE 102. It is open book, and the rules are the same as for the midterm. As usual you will be allocated a seat.\nThere will be 12 questions, each with 10 points, and 90 points are counted as 100%. The questions cover the complete semester, but naturally, some more delicate topics are left out.\nSome hints:\n1. Familiarise yourself with the algorithmic parts of the course, i.e. creating Chomsky normal form, Greibach normal form (for context-free and context-sensitive grammars), turning an NFA into an equivalent minimal, epsilon-free DFA, creating an NPDA or a DPDA, etc.\n2. Familiarise yourself with relationships between models of computation and the corresponding languages: create an accepting TM or a TM computing a particular function (and vice versa), determine a language generated by a grammar, construct regular expressions or grammars for a given language, construct DPDAs/NPDAs, etc.\n3. Familiarise yourself with easier proof techniques: show that a language is not regular or not context-free or not deterministic, show that a function is primitive or partial recursive, find a polynomial or logarithmic reduction, etc.\nThe bulk of the exam contains questions that fall into these three categories.\n',
        'A video of today's lecture will soon become available at\nhttps://media.intl.zju.edu.cn/Media/Play/fdc8bfe9728540e09af321c7b22919931d\n',
        'According to a decision by the senior management the lectures this week Wednesday and Friday will be taught again online.\n',
        'A video of today's lecture will soon be available at\nhttps://media.intl.zju.edu.cn/Media/Play/9923d7da3c7d418292fbd266b32b74281d\n',
        'Due to a change of policy the lecture this Friday, Dec. 10, will be given online.\n',
        'A video of today's lecture will soon be available at\nhttps://media.intl.zju.edu.cn/Media/Play/a87004eea3c549f8b9d59727903c779f1d\n',
        'For the same reasons as for Assignment 10 also Assignment 11 has been reduced.\n',
        'As some students already noticed, Assignment 10 (deadline: December 9) has a non-negligible overlap with content presented in the lectures. It has therefore been modified by cancelling some of the exercises. Please consider the new version.\n',
        'The online teaching period will end next week Wednesday. We will have one more online lecture. The discussions next Thursday and the lecture next Friday will be again in classrooms.\n',
        'A video of today's lecture will soon be available at\nhttps://media.intl.zju.edu.cn/Media/Play/98cdfa6a11ea4d4ba97f4f0b7b4fe67f1d\n',
        'A video of today's lecture is available at\nhttps://media.intl.zju.edu.cn/Media/Play/428991d65d834a22b8efc558bdd98bde1d\n',
        'I will finish the lecture tomorrow at 11:30 to give everyone the possibility to take their required PCR test between 11:30 and 12:30.\n',
        'All deadlines have been slightly shifted.\n',
        'The deadline of Assignment has already been shifted to November 30. In addition, as we will deal with Markov algorithms only on December 1, Exercises 3 and 4 are cancelled.\nFurthermore, for Exercise 2(ii) it suffices to describe several submachines and their interaction.\n',
        'A video of today's lecture will soon become available at\nhttps://media.intl.zju.edu.cn/Media/Play/062eeee3186347148b10452ef3774d711d\n',
        'In addition to yesterday's note all teaching will now be online until further notice. The zoom link for the lectures is\nTopic: ECE374/CS475 Lecture\nTime: This is a recurring meeting Meet anytime\nJoin Zoom Meeting\nhttps://zoom.us/j/89597622332?pwd=emtZYjM2Sld3ZDY5dlpuUEFMK0ZyZz09\nMeeting ID: 895 9762 2332\nPasscode: mod.comp\nFor the discussions the TAs will let you know how to connect.\n',
        'Tomorrow, November 25, the lecture will be held ONLINE.\nHere's the zoom link:\nTopic: ECE374/CS475 Lecture\nTime: This is a recurring meeting Meet anytime\nJoin Zoom Meeting\nhttps://zoom.us/j/89597622332?pwd=emtZYjM2Sld3ZDY5dlpuUEFMK0ZyZz09\nMeeting ID: 895 9762 2332\nPasscode: mod.comp\n',
        'A video of today's lecture is soon available at\nhttps://media.intl.zju.edu.cn/Media/Play/c62a351d0bca426ca2230bb504ff63e31d\n',
        'A video of today's lecture is soon available at\nhttps://media.intl.zju.edu.cn/Media/Play/d9c037d38d4342d8a44f780a72ac24051d\n',
        'Some corrections have been made to the slides.\n',
        'The deadline of Assignment 8 has also been shifted.\n',
        'Due to some technical problems at the beginning of today's lecture no video was recorded.\n',
        'Exercise 3 in Assignment 8 has been replaced by a different one.\n',
        'The deadline of Assignment 7 has been shifted to November 17, 12pm (noon).\n',
        'A video of today's lecture is soon available at\nhttps://media.intl.zju.edu.cn/Media/Play/06c2924c5aa24147a39a037618e87c761d\n',
        'A video of today's lecture is soon available at\nhttps://media.intl.zju.edu.cn/Media/Play/e1151c7bb187420bb1ba39ccd742b8041d\n',
        'The video of today's lecture will soon be available at\nhttps://media.intl.zju.edu.cn/Media/Play/375f203cdadf427c8f66679bb09426791d\n',
        'A video of today's lecture will soon be available at\nhttps://media.intl.zju.edu.cn/Media/Play/93fc8d0e1d1549868b1ac5e9463800cf1d\n',
        'The midterm exam will be held on November 11, 15:00 - 17:00 in LTN-A 418/420. Please be there on time or even a bit earlier.\nThe exam will be open book. You can bring all printed or electronic material you need to the exam. However, you may not use communication software of any kind (WeChat, email, QQ, Dingtalk, etc.).\n',
        'A video of today's lecture is soon available at\nhttps://media.intl.zju.edu.cn/Media/Play/bd9bcaba7116457296e621cd33f879691d\n',
        'A video of today's lecture will soon be available at\nhttps://media.intl.zju.edu.cn/Media/Play/a89a33100d06404daa0bc58b7e9edf0b1d\n',
        'A video of today's lecture will soon become available at\nhttps://media.intl.zju.edu.cn/Media/Play/22fbe505862d44c28329ffe5f3fe3cf81d\n',
        'A video of today's lecture is soon available at\nhttps://media.intl.zju.edu.cn/Media/Play/08546d584ea44455ad22e68d1e924b4f1d\nUnfortunately, it does not show the example on the whiteboard.\n',
        'A video of today's lecture is soon available at\nhttps://media.intl.zju.edu.cn/Media/Play/4d5e6d5366a74a3aad51166c0ff0900a1d\n',
        'A recoding of today's lecture will soon become available at\nhttps://media.intl.zju.edu.cn/Media/Play/e6a57334f286435f97bbcac4dafeb7901d\nThe remarks on sound quality made yesterday apply.\n',
        'This is a reminder that today we resumed teaching on campus in room LTN-B406.\nNonetheless, a video of today's lecture will soon be available at\nhttps://media.intl.zju.edu.cn/Media/Play/453fd58d100240289e2bfaca4957b4cd1d\nIt seems that the sound suffers from the larger distance to the microphone, but it seems still acceptable. There is no recording of the activities on the whiteboard. I strongly advise that you attend the offline lectures. Everything else only makes it more difficult to learn.\n',
        'In Exercise 2 (ii) convince yourself that every word in the language can be written in the form w_1 $ ... $ w_n with w_i in { 0, 1 }*. Then consider conditions that can imply that w_1 ... w_n is not a sequence of consecutive binary numbers. Some conditions are obvious such as w_i = \\epsilon, w_1 ≠ 1, or w_i starts with 0. The decisive condition is to ensure that if w_i represents a binary number b, them w_{i+1} does not represent the number b+1. You can express these conditions by looking at leading or trailing bits. Once you get a set of such conditions, it becomes rather straightforward to construct a context-free grammar creating words, where one of these conditions is satisfied.\nIn Exercise 1(iii) show that words in the language can always be decomposed as w_1 x_1 w_2 x_2 w_3 x_3 w_4, where the w_i are in the language and x_1 x_2 x_3 is one of aab, aba or baa. Once you get such a decomposition, the construction of the grammar is straightforward.\n',
        'We make the following amendments to Assignment 1:\n1) In Exercise 1 only the closure properties for context-free and regular languages are mandatory, and full points (4 each) are given, if these two parts are correct. Any points gained for type-0 and type-1 languages are counted as bonus points.\n2) Only one of Exercises 2 or 3 is counted as mandatory. Points gained for the other of these exercises are counted as bonus points.\n3) Exercise 4 is counted as optional. Any points gained for it are counted as bonus points.\n',
        'A video of today's lecture will soon become available at\nhttps://media.intl.zju.edu.cn/Media/Play/3e0e2e10bd6f4e7cafd2484bc5152b371d\n',
        'A Chinese version of the Hopcroft/Ullman textbook is available at\nhttps://zjuintl-my.sharepoint.com/:b:/g/personal/kd_schewe_intl_zju_edu_cn/EcSomQjgedVAlyjB-mwi5zkBZRC35wSrp7S1PHbwni8C-w?e=TY0x39\n',
        'In (ii) for the case of L_1 only consider languages not containing \\epsilon.\nL_1 is not closed under general subsitution, but if \\epsilon is excluded, it is.\n',
        'Due to several requests the deadline for the submission of Assignment 1 has been shifted to end of Tuesday, September 29.\n',
        'A recording of today's lecture will soon be available at\nhttps://media.intl.zju.edu.cn/Media/Play/52edcecffa83488da45420a7ca8ce0641d\n',
        'A video of today's lecture will soon be available at\nhttps://media.intl.zju.edu.cn/Media/Play/a82e179ff2064b25ac523c20a229e1791d\n',
        'A recording of today's lecture will soon be available at\nhttps://media.intl.zju.edu.cn/Media/Play/8831195d1abe4d7bbe7dc776313c8d991d\n',
        'You must enroll into one of the three discussion groups. So far only half of the students in this class have done this. Please enroll before the discussions start at the latest.\nWith the enrollment you fix the group you will attend throughout the semester.\n',
        'Piazza has been set up for this course. You will find the link in the Contents folder.\n',
        'A recoding of today's lecture will soon become available at\nhttps://media.intl.zju.edu.cn/Media/Play/fcee2351c266469ebb502bb15f47c0a21d\n',
        'The first five lectures (the weeks before the national holiday) are taught online. Here's again the zoom link:\nTopic: ECE374/CS475 Lecture\nTime: This is a recurring meeting Meet anytime, Wed, Fri 10:30 - 12:00\nJoin Zoom Meeting\nhttps://us06web.zoom.us/j/89597622332?pwd=emtZYjM2Sld3ZDY5dlpuUEFMK0ZyZz09\nMeeting ID: 895 9762 2332\nPasscode: mod.comp\n',
        'Klaus-Dieter Schewe is inviting you to a scheduled Zoom meeting.\nTopic: ECE374/CS475 Lecture\nTime: This is a recurring meeting Meet Wednesday 10:30-12:00 and Friday 10:30-12:00.\nJoin Zoom Meeting\nhttps://us06web.zoom.us/j/89597622332?pwd=emtZYjM2Sld3ZDY5dlpuUEFMK0ZyZz09\nMeeting ID: 895 9762 2332\nPasscode: mod.comp\n',
        'Dear Students,\nThe course ECE374/CS475 will start on September 15 with the first lecture. In the first three weeks the lectures will be given online (the zoom link will be provided in a separate announcement). Other organisational matters will be announced in the first lecture.\nDiscussions will held in three parallel groups by teaching assistants Liu Bowen, Liu Xiaolu and Li Jingshu. These groups will also be used to allocate assignments. You must enroll into one of the three discussion groups. As we expect ~67 junior students in the course, each discussion group is currently limited to maximum 23 members.\nSenior students should take CS475 instead of ECE374 (unless they repeat the course).\nSee you on September 15.\nKlaus-Dieter Schewe\n',
        'Hello Students,\nAs a reminder, due to the Mid-Autumn festival, remote lecture will not be held today (9/21). The make-up lecture will be on Sunday 9/26 at 9:00 AM - which will be treated as a Tuesday (see academic schedule) https://zjui.intl.zju.edu.cn/calendar/1391. Make sure you come to lab prepared to demonstrate your simulation for Lab 2 this week as we will discuss Lab 3's circuit on Sunday's lecture which will be held on Zoom.\nThe link is provided in the lecture slides, but for your reference, the link for the remote lectures is:\nhttps://illinois.zoom.us/j/82954602523?pwd=UGM3Zkx4U0NSOU9lWDVoaVlWTkRlZz09\nPlease be sure to check the calendar, as the in-person lectures will be given by Prof. Li and still be held in LTE 102.\n',
        '',
        'The following test has been made available in Content: Week8 Quiz.\n',
        'Dear Students,\nThis message will give details about the final Listening and Reading exam, final Wiring exam for ZJE students and the final Spoken Presentation assessment. \nAfter consideration and discussion with the Center for Academic Affairs, it has been decided that the final Listening and Reading exam and the Writing exam for ZJE students will be postponed until all students return to campus in time for the Fall/Autumn semester in September.\nThe reason for this decision relates to the broader decision by Academic Affairs for all courses to only give exams that can be carried out online. Exams and assessments which cannot be done online will instead be delayed until sometime in September. \nFor Integrated English 2 this means that the final Listening & Reading exam and the Writing exam will not take place on May 25th as originally planned.\nThis has no effect on the final speaking assessment which remains the same.\nWe understand that this may cause some concern for those students who worry about how this delay will affect their GPA. However, this is something that can be discussed with the Center for Academic Affairs and your institute at a later date.\nFor now, you just need to know that in your IE2 class, the last major task of this semester is to complete your final presentation and submit it before the deadline on the 22nd of May.\nIn the summer vacation period, you should dedicate a little time each week to practice for TOEFL or IELTS tests to prepare for the final exams in September.\nIf you have further questions about the final assessments, please use the QnA forum here on blackboard and we will try to answer you as soon as possible.\n  All the best,\nYour integrated English Instructors\n',
        'In a few hours, the Week 9 content folders will open and it will be ready for your mid-term presentation. The *only* required activity is your midterm presentation in the Speaking/Week 9 folder. This will be your first graded activity in this course.\nYou are strongly encouraged to go back to previous weeks and review lectures, reading tasks, and the reading task responses of your classmates before recording your video.\nIf you have questions, first review the Q&A forum to search if your question has already been answered. If not, you can post a new question.\nPlan ahead and do not wait until the last minute to submit your presentation. Expect technical difficulties and for the network to be slow. The scores of late submissions will be reduced by 5% per day that it is late.\nAs always, you are allowed multiple submissions up to the deadline.\n',
        'Dear students,\nAfter the first few weeks, I have some additional tips and reminders to help the course run more smoothly for all of us.\n1) Do the assigned pre-reading and watch the lesson videos before you do your presentation or writing assignment for the week. Your feedback will be given assuming that you've learned from the lesson materials, so to avoid the embarassment and waste of your time, please prepare yourself appropriately. If it's clear that you did not pay attention to weekly lessons, you will not receive credit for that week's work until you do.\n2) Submit your homework in the correct place. If it is an assignment for Week 4, it belongs in the assignment submission for week 4 and not week 3. If you want credit for your work, it must be in the right place. Please note, also, that your homework submissions are \'SUBMISSIONS\' and not \'COMMENTS.\' It is important to pay attention to where you put your work for it to be managed efficiently. See the image below if you are not sure about the differences between these two terms.\n2.1) Concerning presentation submissions for all students, starting week 5 with Presentation 2, ALL submissions must be via OneDrive with the link as described in this important announcement from week 3. It takes far too long for us to download videos that are submitted as an attachment. Starting week 5, any uploaded/attached presentations will receive an automatic zero until you submit it correctly  by uploading it to OneDrive and linking it. We appreciate your flexibility and support in this. I understand this will be unfamiliar to some of you. Please take the time to familiarize yourself with the education tools your campus provides. I have curated some documentation (in both English and Mandarin) for you to review on a recent Q&A thread. If you need further help with this, please contact IT services for help.\n2.2) Concerning writing submissions for ZJE students, feel free to continue attaching Word documents if this works better for you.\n3) If you experience any technical difficulties, such as not being able to submit an assignment in the right place, let us know immediately via the WeChat group or email, and wait to submit it in the correct place. Many students are submitting work in other, incorrect, weeks/folders without telling us about the problem. This will result in no participation credit for the missing week's material until it is submitted correctly. For example, homework for Week 4 speaking needs to be submitted in the week 4 speaking assignment. If you put it anywhere else, it will get lost and uncounted.\nIf you have any questions or concerns, you may email me at william@intl.zju.edu.cn or contact any of us on the WeChat group. The Q&A forum still works, but the other options often receive a faster response.\nThanks, and keep up the consistent work!\nWill\n',
        'I've opened up a WeChat group for all sections of Integrated English 2 combined. We will continue to use Blackboard as much as possible for submissions, but, this WeChat group will be a more familiar way to connect with us and get support if you have any questions or problems with the course materials or Blackboard.\nJoin us:\nThis should largely replace the Q&A forum, but I suspect all of you will be much more comfortable with WeChat.\n',
        'Some of you may be experiencing an error (\'failure to save message\') when you submit discussion forum posts. We urge you to contact ITS to resolve this. However, I can offer a tip to make sure you don't lose your writing when errors like this happen.\nCompose your response in another app, like Notepad, first, and then copy it over when you're ready. Many things can happen that might erase the information in a webpage textbox, and not all browsers are designed to save what you type.\nHopefully, ITS can provide a solution soon.\nP.S., a couple of things to remember\nA) When asking us, or anyone for that matter, for assistance, please provide enough information for us to understand the problem. We are powerful and magical creatures, but alas we cannot yet read minds. That goes for literally every person you need to ask for assistance: ITS, other professors, your bank,  etc.\nB) If it is not urgent or personal, use the Q&A forum, please! It's much easier to answer a question once and let all students read the question and response than it is to respond to the same issue hundreds of times.\n',
        'Dear Undergraduate Students,\n  Welcome to the new semester and to Integrated English 2. As you know, this semester the university will be running all courses online. I know this adds extra challenges to your studies, but I'm confident that we can make the most of it.\n  Integrated English 2 this semester is going to make use of a range of online tools and methods to deliver English teaching content and training tasks. These are designed specifically for you to improve and practice the English skills you need for academic success.\n  There are a few important things to know about this online course and several points you should consider about.\nHow you will interact with the online course\nMost of the online course will be delivered via blackboard. There are three main ways you will interact with the course materials:\nThe speaking course this semester focuses on Presentation skills.\nThe writing course is about Science report writing.\n  Each week you will have a new set of online tasks to complete. These will include a video lecture to watch. These will be around 20 minutes.\nYou will usually have reading or listening tasks to do; this is similar to last semester but this time you will have to post your answers to tasks on blackboard.\nZJE students will also have extra instruction each week for science writing and will be given a writing practice task each week.\nWe have discussion forums on Blackboard for you to post your answers to tasks. We can then read your responses and where appropriate offer feedback and advice on your English.\n  The discussion forums will be an important point of interaction with your English professors. Through the forum you can ask questions about the course, questions about individual tasks, and you can interact with other students. You can see other students’ work and read feedback from professors. This should help everyone learn things about their English as well as stay in touch with what’s happening with the course.\nHow you will be assessed\nThis semester is a very special case and the assessments might have to change as a result.\nSpeaking: Right now, the plan is to have you complete two speaking assessments online by recording and uploading video recorded spoken presentations. One short talk and one longer presentation with visuals.\nOver the course of the semester, you will submit 3 non-graded practice presentations. You must record these as video files to submit on Blackboard. Instructions on how to do this will be provided.\nFor assessment you will submit 1 graded mid-term recorded presentation, and for your final speaking assessment you will submit a recorded presentation with visual aids (using PowerPoint slides, etc.).\n  Listening and Reading: Right now, we anticipate that by the end of the semester, everyone will have returned to campus and be able to sit the final exam as normal. If that is not the case then we will have to find an alternative way to run the final listening and reading exam online. But this has not been decided yet. So, for now do not worry as much about this test.\nZJE Writing: As was the case last semester, ZJE students will also take the extra writing component of Integrated English 2. The situation for the writing exam is the same as for listening and speaking above\nNow, throughout the semester it is very important that you pay attention to your emails and blackboard announcements and keep track of the tasks and work you are doing to improve your English. Whenever you are unsure what to do, you can ask using blackboard or by sending an email.\n    Head over to the Content section of blackboard and access the week one speaking practice materials to get started.\n  All the best for this unusual and interesting new semester.\n  Sincerely,\nYour English Professors.\n \nCourse Link/Content/Speaking lessons/Week 1: February 17, 2020 -- February 21, 2020\n',
        'Phys213 has prelabs, please finish it before class.\n',
        'Notes for Lecture 12 were updated\n',
        'LTW 102  Discussion sections 4,5\nLTW 201 Discussion section 6\nLTE 102 Discussion sections 1-3\n',
        'Midterm will he held this Sunday, April 25th, starting 6 pm. Duration - 2 hours.\nLocations:\nLTE 102   - Discussion groups  1-3,\nLTW 102 -  Discussion groups  4-5,\nLTW 201 -  Discussion group  6\nLecture are rescheduled as follows:\n  Friday, April 23rd - Q/A session, optional\n  Monday, April 26th       - No class\n  Wednesday, April 28th - Lecture 10\n  Friday, April 30th          - Lecture 11\n',
        'Date and time of Midterm exam will be decided today during Discussion sessions.\n',
        'In this course, every student is allowed to create and use HIS OWN hand-written formula sheet (A4, 1 side) during quizzes and exams.\nThe standard Formula sheet will not be provided.\n',
        'Attention! For the next to weeks, the lectures are scheduled as follows:\nFriday, April 2nd - No lecture\nWednesday, April 7th - Lecture 3\nFriday, April 9th - Lecture 4\nDon't forget to complete pre-lectures and checkpoints at Smart.Physics in time.\n',
        'Lectures start next Monday, March 29\nEast Hall, 10:00-11:00\n',
        'Dear all,\nPhys214 lab1 will be in room E417 of lab building, please note.\nThe rest 3 lessons will be in E521/E519.\n',
        'Dear all,\nThe first lab lesson will be on next week, please note.\nNo prelabs for phys214 lab.\nCourse Link/Content/phys214 lab class schedule\n',
        'Dear ALL,\nPlease help finish the course evaluation through the link below.\nhttps://forms.office.com/Pages/ResponsePage.aspx?id=xSAmKRCuU0Wsz2jsgDJQCOnMVLQF6hhIhjqiVXqkhG1UNExTN1U5OFZXUUNQWUtHWFM1OTgxWVVaUi4u\nAnyone who finishes the evaluation and send the screen shot (after you finish it) to your Teaching Assistant through email (only email is acceptable, other ways, such as wechat or others are not acceptable ), will get 0.5 extra point for your final exam. The deadline is 16 May, 5pm.\nThanks\nWenchao CHEN\n',
        'Dear All,\nThe final exam is scheduled on   April 23, 6pm-8pm. \nExam rooms and seats are arranged as in the attached file (in the \'content\'), please find your room and seat number.\nFor those who have conflicts, I already contact you individually to secure another time slot. \nThere are some tips/rules for you.\n1.No cheating sheet, no draft paper are allowed. I will prepare the formula sheet for you.\n2. No electronics besides calculator. \n3. Don't be late. There will be no make-up exam. If you don't come, it will be considered as you give up.\n4.Final exam example is also posted for you reference.\nIf you have any question, contact me through wenchaochen@zju.edu.cn\nWenchao CHEN\n',
        'Dear ALL,\nSince some of you have conflicts on   April 16th. We have to tentatively reschedule the final exam on April 23, 6pm-8pm. If you have any conflict, please contact me through wenchaochen@zju.edu.cn.\nThanks\nWenchao CHEN\n',
        'Dear ALL,\nThe final exam is tentatively scheduled on April 16th, Friday, from 6:00pm to 8:00pm. If you have any conflicts, contact me before April 2ed through wenchaochen@zju.edu.cn\nThanks\nWenchao CHEN\n',
        'Dear ALL\nThe midterm will be on Friday 6-7:20pm. Please attend on time. If you don't attend, that will be considered as \'you give up the midterm exam\', and no make-up exam will be made.\nThanks\nWenchao Chen\n',
        'Dear ALL,\nThe midterm is scheduled on March 19, 6pm-7:20pm, in Lecture Theater East 102; 201; 204. Midterm exam covers Lecture 1-12.\nGood Luck.\nWenchao CHEN\n',
        'Dear All,\nMidterm Term Exam is scheduled on March 19,Friday, 6pm-7:20pm, which covers Lecture 1- 12, Location will be announced later.\n',
        'Dear ALL,\nPlease log into: https://smart.physics.illinois.edu/\nCheck whether you are enrolled in PHY214 or not. If you have problem, contact me before Wednesday.\nEmail: wenchaochen@zju.edu.cn\nWenchao CHEN\n',
        'Dear students,\nPlease fill the form through\nhttps://f.wps.cn/w/cXci677W/  or  with the link in the Wechat group.\nIf you have class on the evening of April 23.\nThanks\n',
        'Office hour is from 4pm to 4:40 pm on Monday. Send an email before you come in case I am not in office.\nOffice: ZJUI Building B 410\n',
        'Dear all,\nPlease print the discussion material before the discussion session or use your tablet.\nThank you.\n',
        '如果你登录系统有问题，找不到课程尽快联系我 https://smart.physics.illinois.edu/\n提供你的名字，uiuc NetID，发我邮箱。\nEmail: wenchaochen@zju.edu.cn\n这周五以后不再受理！\nWenchao CHEN\n',
        '各位同学，本周五（4月1日）晚18:00-20:00，书院（2号）多功能厅，听中国工程院院士、浙江大学能源工程学院院长高翔教授线上分享成长经历，了解“院士是怎样养成的？”\n请愿意参加的同学进入以下链接，扫描其中的二维码报名，提前10分钟进场，并在讲座结束后24小时内提交200-300字的感言。\nhttps://mp.weixin.qq.com/s/rS9SZnqOp7MuvLxxQF-_fg\n  特别提醒：未报名或未提交感言的同学将不能获得形策II本次课程分数。\n王玉芬\n2022.3.30.\n',
        'Hi there, we residential college starts our online course now.\nHere, you can view virous interesting courses related to RC, hope you can enjoy it and don't hesitate to reserve and give us a thumb up :)\n'
    ]
}
]
module.exports={
	data:data
}