const data = [
{
    "Title": [
        "Getting your MT2 papers",
        "Teaching Assistants Sought",
        "Final Exam Model Answers",
        "Final",
        "Presentation Schedule",
        "Last Lectures",
        "CA2 Ex.4",
        "Course Feedback",
        "CA2 deadline",
        "Graphs in CA2",
        "Submission of MT2",
        "New policy",
        "Final Presentations -- Schedule",
        "Final Exam",
        "Midterm 1 Paper",
        "Midterm 2",
        "B+ Tree (Definition and Confusion)",
        "Lab 9 and Programming Assignment 2",
        "Assignment 6, Ex. 3",
        "Assignment 5",
        "Assignment 5, Ex. 1",
        "Midterm 1 -- Note on Cheating (Important)",
        "Assignment 3",
        "More on Midterm 1",
        "Assignment 3",
        "Hint for Ass.3, Ex. 4(ii)",
        "More on Midterm 1",
        "quarantine?",
        "Midterm Exams",
        "Assignment 3 and Programming Assignment 1",
        "Assignment 2 deadline",
        "Office Hours / Groups / Labs",
        "Welcome to CS 225",
        "New test",
        "Important announcement regarding the final assessments for IE2",
        "Welcome to mid-terms!",
        "Reminder: Homework submissions",
        "Integrated English 2 WeChat Group",
        "Submission errors",
        "Welcome to Spring Semester 2020",
        "Math 286 Grades",
        "Math 286 Course Evaluation",
        "Deadline for TA application for Calculus III in Fall 2021",
        "Solutions to the final exam",
        "Information about the Final Examination",
        "About Lectures 55, 56",
        "About lab presentations today, 5:00 - 8:20 p.m.",
        "Lab Presentation Schedule",
        "Sample final exams",
        "About Homework 13",
        "Deadline for Homework 11",
        "Next lecture(s)",
        "Lecture Slides on LInear Algebra",
        "About Homework 11",
        "About late HW submissons",
        "Lab Project",
        "Discussion Group 1 (Niu Yiqun) moved to a later date",
        "Information about the midterm",
        "About Homework 6",
        "Piazza Math 286 Class",
        "Midterm date",
        "Remote Learning",
        "Homework 3",
        "About Homework 2",
        "Office hours",
        "Math 286 discussion groups",
        "New class schedule",
        "notice of phys212 labs",
        "Phys213 prelabs",
        "Updated notes",
        "Correction for Midterm Location",
        "Midterm's and lectures schedule",
        "About Midterm",
        "Regrding the Formula Sheet(s)",
        "Lectures schedule arrangement",
        "Lectures begin",
        "classroom of phys214 lab1",
        "Class schedule of phys214 lab",
        "Bonus Points for Final Exam-If you finish the task below",
        "Final Exam",
        "Tentative Schedule of PHY 214 Final Exam",
        "Final EXAM",
        "Reminder: Midterm Exam will be on Friday 6pm-7:20pm",
        "Midterm Term Exam on March 19, 6pm-7:20pm",
        "Midterm Term Exam on March 19, 6pm-7:20pm",
        "Smart Physics System:https://smart.physics.illinois.edu/",
        "survey for conflicts of Final Exam",
        "Office Hour",
        "Discussion material",
        "最后提醒：https://smart.physics.illinois.edu/",
        "Residential College online course collection just open up!"
    ],
    "Posted On": [
        "Friday, May 28, 2021 7:37:31 PM CST",
        "Saturday, May 22, 2021 3:55:16 PM CST",
        "Saturday, May 22, 2021 3:51:39 PM CST",
        "Friday, May 21, 2021 3:00:38 PM CST",
        "Monday, May 17, 2021 2:46:30 PM CST",
        "Saturday, May 15, 2021 8:56:11 AM CST",
        "Friday, May 14, 2021 8:11:48 AM CST",
        "Thursday, May 13, 2021 9:07:37 AM CST",
        "Tuesday, May 11, 2021 8:06:44 AM CST",
        "Tuesday, May 11, 2021 8:02:51 AM CST",
        "Tuesday, April 27, 2021 11:02:09 PM CST",
        "Monday, April 26, 2021 5:27:04 PM CST",
        "Monday, April 26, 2021 5:24:14 PM CST",
        "Monday, April 26, 2021 5:14:15 PM CST",
        "Monday, April 19, 2021 2:29:17 PM CST",
        "Monday, April 19, 2021 10:26:29 AM CST",
        "Monday, April 19, 2021 10:14:07 AM CST",
        "Saturday, April 10, 2021 1:28:38 PM CST",
        "Wednesday, March 24, 2021 12:27:17 PM CST",
        "Sunday, March 21, 2021 4:02:14 PM CST",
        "Saturday, March 20, 2021 6:55:04 PM CST",
        "Wednesday, March 17, 2021 8:32:14 AM CST",
        "Wednesday, March 10, 2021 2:18:47 PM CST",
        "Monday, March 8, 2021 1:58:21 PM CST",
        "Sunday, March 7, 2021 12:25:55 PM CST",
        "Sunday, March 7, 2021 12:23:22 PM CST",
        "Wednesday, March 3, 2021 1:39:47 PM CST",
        "Sunday, February 28, 2021 6:30:28 PM CST",
        "Friday, February 19, 2021 10:43:17 AM CST",
        "Monday, January 25, 2021 2:39:20 PM CST",
        "Tuesday, January 19, 2021 9:35:57 AM CST",
        "Thursday, January 7, 2021 9:29:53 AM CST",
        "Monday, January 4, 2021 11:57:38 AM CST",
        "Friday, April 9, 2021 12:30:00 PM CST",
        "Saturday, May 16, 2020 12:25:10 PM CST",
        "Monday, April 13, 2020 2:25:53 AM CST",
        "Wednesday, March 11, 2020 4:31:57 AM CST",
        "Monday, February 17, 2020 5:31:15 PM CST",
        "Monday, February 17, 2020 4:40:31 PM CST",
        "Sunday, February 16, 2020 3:05:35 PM CST",
        "Monday, June 14, 2021 12:11:53 PM CST",
        "Tuesday, June 1, 2021 3:16:16 PM CST",
        "Sunday, May 30, 2021 3:39:45 PM CST",
        "Sunday, May 30, 2021 3:32:00 PM CST",
        "Friday, May 21, 2021 12:54:29 PM CST",
        "Friday, May 21, 2021 11:49:12 AM CST",
        "Tuesday, May 18, 2021 2:28:01 PM CST",
        "Wednesday, May 12, 2021 4:36:48 PM CST",
        "Wednesday, May 12, 2021 3:35:46 PM CST",
        "Friday, May 7, 2021 3:39:04 PM CST",
        "Wednesday, April 28, 2021 2:55:55 PM CST",
        "Tuesday, April 27, 2021 8:21:22 PM CST",
        "Tuesday, April 27, 2021 8:22:05 PM CST",
        "Tuesday, April 27, 2021 3:36:05 PM CST",
        "Thursday, April 15, 2021 11:06:19 AM CST",
        "Thursday, April 15, 2021 10:56:05 AM CST",
        "Thursday, April 8, 2021 3:44:42 PM CST",
        "Tuesday, March 30, 2021 12:30:18 PM CST",
        "Tuesday, March 16, 2021 3:24:12 PM CST",
        "Sunday, March 14, 2021 12:10:15 PM CST",
        "Thursday, March 4, 2021 10:27:32 PM CST",
        "Monday, March 1, 2021 3:20:52 PM CST",
        "Sunday, January 31, 2021 11:52:23 AM CST",
        "Monday, January 18, 2021 3:39:16 PM CST",
        "Saturday, January 16, 2021 11:25:16 AM CST",
        "Wednesday, January 13, 2021 2:47:15 PM CST",
        "Friday, October 9, 2020 1:39:53 PM CST",
        "Thursday, September 24, 2020 4:42:51 PM CST",
        "Tuesday, April 6, 2021 10:03:46 AM CST",
        "Saturday, May 8, 2021 8:58:22 AM CST",
        "Sunday, April 25, 2021 5:40:47 PM CST",
        "Sunday, April 25, 2021 5:41:38 PM CST",
        "Thursday, April 15, 2021 5:21:52 PM CST",
        "Thursday, April 8, 2021 3:29:06 PM CST",
        "Thursday, April 1, 2021 5:50:10 PM CST",
        "Friday, March 26, 2021 2:44:27 PM CST",
        "Friday, January 15, 2021 2:56:12 PM CST",
        "Friday, January 15, 2021 11:18:29 AM CST",
        "Wednesday, May 12, 2021 7:50:41 PM CST",
        "Sunday, April 18, 2021 9:00:10 PM CST",
        "Friday, April 2, 2021 2:17:11 PM CST",
        "Monday, March 29, 2021 3:17:18 PM CST",
        "Thursday, March 18, 2021 10:49:04 AM CST",
        "Friday, March 12, 2021 11:11:57 AM CST",
        "Friday, March 5, 2021 11:46:51 AM CST",
        "Monday, January 11, 2021 5:48:14 PM CST",
        "Tuesday, April 13, 2021 10:12:10 PM CST",
        "Wednesday, January 20, 2021 11:29:02 AM CST",
        "Wednesday, January 13, 2021 9:08:45 PM CST",
        "Wednesday, January 13, 2021 11:14:51 AM CST",
        "Tuesday, February 25, 2020 9:20:21 AM CST"
    ],
    "Posted By": [
        "熊能 (Xiong Neng) ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "江凤清 (Jiang Fengqing) ZJU-UIUC Institute",
        "江凤清 (Jiang Fengqing) ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "李翔 (Li Xiang) ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "江凤清 (Jiang Fengqing) ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "Klaus-Dieter Schewe ZJU-UIUC Institute",
        "林妙蓉 社会学",
        "Robert Holmes Liberal Arts&Science college",
        "William Denny 浙江大学国际联合学院",
        "William Denny 浙江大学国际联合学院",
        "William Denny 浙江大学国际联合学院",
        "William Denny 浙江大学国际联合学院",
        "Robert Holmes Liberal Arts&Science college",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "Thomas Honold 国际联合学院(海宁国际校区)",
        "夏焕新 国际联合学院(海宁国际校区)",
        "夏焕新 国际联合学院(海宁国际校区)",
        "夏焕新 国际联合学院(海宁国际校区)",
        "Oleksiy Penkov ZJU-UIUC Institute",
        "Oleksiy Penkov ZJU-UIUC Institute",
        "Oleksiy Penkov ZJU-UIUC Institute",
        "Oleksiy Penkov ZJU-UIUC Institute",
        "Oleksiy Penkov ZJU-UIUC Institute",
        "Oleksiy Penkov ZJU-UIUC Institute",
        "Oleksiy Penkov ZJU-UIUC Institute",
        "夏焕新 国际联合学院(海宁国际校区)",
        "夏焕新 国际联合学院(海宁国际校区)",
        "陈文超 国际联合学院(海宁国际校区)",
        "陈文超 国际联合学院(海宁国际校区)",
        "陈文超 国际联合学院(海宁国际校区)",
        "陈文超 国际联合学院(海宁国际校区)",
        "陈文超 国际联合学院(海宁国际校区)",
        "陈文超 国际联合学院(海宁国际校区)",
        "陈文超 国际联合学院(海宁国际校区)",
        "陈文超 国际联合学院(海宁国际校区)",
        "许欢 (Xu Huan) ZJU-UIUC Institute",
        "陈文超 国际联合学院(海宁国际校区)",
        "许欢 (Xu Huan) ZJU-UIUC Institute",
        "陈文超 国际联合学院(海宁国际校区)",
        "谢佳妮 后勤集团"
    ],
    "Posted To": [
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "CS225:DataStructures-LEC-1439(20-21)",
        "GCL200:FrameworksforInequality-LEC-1518(20-21)",
        "Integrated English Ⅱ",
        "Integrated English Ⅱ",
        "Integrated English Ⅱ",
        "Integrated English Ⅱ",
        "Integrated English Ⅱ",
        "Integrated English Ⅱ",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "MATH286:Introto Differential EqPlus-LEC-1370(20-21)",
        "PHYS212:University Physics: Elec& Mag-Lab:20-21(1069-1070-1071)",
        "PHYS212:University Physics: Elec& Mag-Lab:20-21(1069-1070-1071)",
        "PHYS213:Univ PhysicsThermal Physics-Lab",
        "PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)",
        "PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)",
        "PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)",
        "PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)",
        "PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)",
        "PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)",
        "PHYS213:UnivPhysics:ThermalPhysics-LEC-1396(20-21)",
        "PHYS214:Univ Physics-Quantum Physics",
        "PHYS214:Univ Physics-Quantum Physics",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "PHYS214:UnivPhysics:QuantumPhysics-LEC-1409(20-21)",
        "Residential College"
    ],
    "Stipulate": [
        "Dear all,If you want to get your MT2 paper, please come to library café 13:00-14:30 tomorrow (May 29th Sat).\nThanks,\nCS 225 faculty\n",
        "If you are interested in becoming a Teaching Assistant next semester for MATH 213 Discrete Mathematics, send an e-mail to me. An official call for TAs from ZJUI will come soon.\n",
        "Model answers for the final exam will be available tomorrow. Just take a look at BB.\n",
        "The final exam is open book and partly computer-based.\nYou need to bring a laptop. You may use a tablet.\nYou may bring any paper-based learning material (lecture slides, textbooks, printed model answers of assignments, additional texts, handwritten notes).\nCell phones are forbidden.\nYou may access stored e-books on your laptop or tablet.\nApart from access to Blackboard for download of the exam script and templates for programming exercises and upload of answers the use of communication software (WeChat, email, QQ, WebEx, zoom, web search, etc.) is not allowed.\nYou may use BB to access any of the uploaded material for this course.\nFor anything not covered by the list above ask one of the proctors during the exam.\n",
        "Pay attention to your group time slot, for both presenter group and grader group. Each group would help to evaluate another group's presentation, make sure your group be ready for both.  \nAnd come a bit early than your slot (maybe about 10 mins). Absence or late may get punishment since we value both your time and the staffs'.\n",
        "The lectures on Tuesday, May 18 and on Wednesday, May 19 (as much as necessary) will be dedicated to a revision as preparation for the final exam. The lecture on Monday, May 17 will round up Section 11.\nThe final exam will contain 8 conceptual questions (10 points each) and 3 programming questions (20 points each). If you reach 60 points, this will be counted as 100%.\nApart from Sections 1 and 11 all other sections are covered in the exam; some sections are covered by more than one question. In Section 10 only Subsection 10.1 is covered.\n",
        "It looks like Ex.4 in CA2 causes lots of problems, mainly problems to understand what to do. As the end of the semester is near, we cannot shift the deadline. So we take Ex.4 out of CA2. If you have already done this Exercise, we may give you some bonus for it. For now we stop the discussion of CA2.\n",
        "As every semester you are invited to provide feedback on the course. The questionnaire is available at\nhttps://forms.office.com/Pages/ResponsePage.aspx?id=xSAmKRCuU0Wsz2jsgDJQCOnMVLQF6hhIhjqiVXqkhG1UNExTN1U5OFZXUUNQWUtHWFM1OTgxWVVaUi4u\nAlternatively, you may also use the QR course placed under Content/Feedback.\nPlease return your feedback by May 16.\nPlease also answer questions Q15 \"How much time did you spend on lectures, labs, homework assignments, literature study and exam preparation?\" Give a realistic picture, so it can help to adjust future instances of this course.\" and Q16 \"Describe, which aspects of the course you found challenging, and which aspects were rather simple. Which topics should be emphasized more, which less?\".\n",
        "In addition to the message postage by Fengqing Jiang do you very best on this computing assignment, even if you feel that it is not perfect. We will NOT extend this deadline. \n",
        "Ignore the last sentence in CA2 concerning graphs. It does not make sense.\n",
        "Please submit the empty coding template of MT2 even if you didn't try it so that we could assign your grade on BB. Otherwise, you cannot get any score for MT2.\nFor those who already submitted something for MT2, please ignore this message.\nThanks!\n",
        "According to a new policy of ZJUI extra hours spent for midterm exams shall be compensated. Therefore, the last four lectures of the semester (not counting revision sections) will be optional. These last lectures will be given, but attendance is voluntary, and the lecture material will not be part of any assessment.\n",
        "The schedule for the final presentations in the labs on May 17 and 19 is available on BB (Labs 13/14).\nBesides their own presentation each team will be involved in the assessment of one other team. The assessment form is also available on BB.\n",
        "The final exam is scheduled for May 22, 9:00-12:00. It will be conducted in the same way as the midterms with a mixture of conceptual and programming exercises.\nThe last two lectures of the semester (May 18 and 19) will be reserved for revision and questions concerning the final exam.\n",
        "Dear all,\nWe would deliver back your midterm 1 paper back in today's discussion, please come to your assigned discussion room to get yours.\n",
        "The second midterm is scheduled for April 27, 20:00-22:00 in LTW 102 and LTE 102. The room arrangement is as follows:\nLTW 102: groups 1-18\nLTE 102: groups 19-31\nDespite some requests there will be no sample available. There was no MT2 last year. In addition, to avoid another disaster we will implement a few changes:\n1) There will be fewer programming tasks. The additional time needed for dealing even with simple problems in C++ is far too high and risky.\n2) Instead, we will have questions that ask you to apply the basic algorithms taught in the course on specific examples.\n3) The midterm is to cover the sections 6, 8 and 9 (until April 23) with a strong focus on Sections 8 and 9. B- and B+-trees will not be covered.\n",
        "There have been some confusing posts concerning the notion of B+-tree. There are indeed different definitions in the literature. In the lectures we used the definition commonly employed in the context of databases, the most prominent and decisive application case for B+-trees. According to this definition not all keys appear in the tree nodes, and pointers from leave do not point to the stored record with the given key, but to blocks. The reason for adopting such a definition is that otherwise there would be a lot or reorganisation effort needed in the B+-tree.\nThe are definitions in the literature, where the real data records are de facto ignored, and all keys appear in the leaves. This is just a simplification, which could be used, when the data is not kept in secondary storage.\nUnfortunately, no full implementation in C++ is available for the advanced notion of B+-tree; CS225 last year provided a Python implementation. You may simplify your handling of B+-trees by adopting one of the available simplified implementations, i.e. you may dispense with secondary storage issues.\n",
        "Lab 9 deals with B-trees and B+trees and even their combined use. It turns out to be impossible to provide a fresh implementation in time; this is just too complex. Instead use a C++ implementation from github---there are several available.\nDo the same for Programming Assignment 2, but indicate where you got the code. Integrating the github code with your code from Programming Assignment 1 and extending it with some non-trivial queries is difficult enough.\n",
        "As the recursive implementation of insert and delete has already been provided, the exercise has been modified. You only need to sketch the iterative implementations and discuss the differences. No coding is required. This should also compensate for the hassle with Assignment 5.\nNonetheless, you are still encouraged to explore iterative versions of the insert, find and delete operations on AVL trees, but they they are not part of the assignment.\n",
        "In view of the misunderstanding the deadline of Assignment 5 is shifted by 2 days.\n",
        "There seems to be a big misunderstanding here. This exercise was meant to be conceptual: describe the implementation, but don't implement it in C++.\nFibonacci heaps appear in the programming assignment 1; that suffices.\n",
        "The rule was clear: no communication with WeChat or similar means is permitted. Nonetheless, some students violated this rule. Those who did will receive 0 for the midterm.\nIn addition, cheating students are warned that any further cheating in this course will lead to a grade F. This in in accordance with Item 12 in the syllabus. According to the policy of ZJUI further actions by the institute cannot be excluded.\n",
        "The model answer for Assignment 3, Ex. 4(ii) has been modified. The previously given hint is misleading and does not work. The trouble the exercises caused will be taken into consideration in the grading.\n",
        "Organisation. Concerning the organisation of midterm 1, the conceptual question will be paper-based to avoid the necessity of scanning. Computing questions will need to be uploaded.\nYou will need your laptop. As power outlets are limited in LTW and LTE please ensure that your laptop is fully charged to survive the two hours exam. Should your battery be already so old that it cannot last for 2 hours, you better bring some long enough power cable.\nScope. Concerning the scope, the exam covers what we have dealt with in the lectures and labs, i.e. sequence data structures and associated algorithms, priority queues and a bit of hashing. You are of course allowed to use the code that has been provided in the labs, as we do not expect that this can all be re-implemented with only 2 hours.\nThe provided sample midterm exam script from last year gives you some hints what to expect. Of course, you will be expected to use C++ instead of Python. Further note that last year priority queues were only dealt with later in the lectures, so they did not appear in the first midterm. This year, however, we have not yet handled tries or binary search trees, so questions in this direction are of course not part of the midterm.\n",
        "As everyone seemed to have some problem with Ex.4, we shift the deadline by one day.\n",
        "Due to multiple requests here's a bit more help for this exercise.\nUse a divide and conquer approach. That is, when you add k new elements to a heap, add them at the end (equivalently, add them as new tree leaves). The heap is a binary tree, so you actually add k_1 elements to the left subtree of the root and k_2 new elements to the right subtree, with k_1 + k_2 = k. Proceed recursively until you get to trees of height ≤ 2. Whenever you have insert k_1 (k_2) elements into the subtrees, you only need to sift down the root to obtain a heap. Then you can use induction for the proof of the complexity statement. For the induction base you have to explore multiple cases for trees of height ≤ 2, for which you can minimize the number of swap to be just k+1.\n",
        "As the question came up, both midterm exams will be computer-based comprising a mixture of conceptual and programming exercises. You need to bring your laptop. You need to be able to access BB, as the exam script will become visible on BB right in time for the exam. Upload of answers is done in the same way as for all homework assignments. The exam is open book, so you can also bring all your lecture material, textbooks, etc. For the programming exercises you will be requested to extend or modify existing codes, so make sure that all sample code is available.\n",
        "I have no information if any student spent time in a medium- or high-risk area and therefore needs to spend some time in quarantine. If that is the case, please let me know asap. I set up a zoom meeting (see details below) in case we need to give students in quarantine the chance to participate. The zoom meeting times are the same as the lecture times.\nTopic: CS 225 (temporary)\nTime: This is a recurring meeting\nJoin Zoom Meeting\nhttps://zoom.us/j/94378167366?pwd=bE1wdTVDZ1hhTVgwSVJqRitCeEdZUT09\nMeeting ID: 943 7816 7366\nPasscode: 071769\n",
        "The dates for the two midterm exams have been fixed.\nMIDTERM 1: Tuesday, March 16, 20:00-22:00 (2 hours)\nRooms for Midterm 1 are LTE 102/103 (Groups 1-15) and LTW 102/103 (Groups 16-32).\nMIDTERM 2: Tuesday, April 27, 20:00-22:00 (2 hours)\nRooms for Midterm 1 are LTE 102/103 (Groups 1-15) and LTW 102/103 (Groups 16-32).\n",
        "The first programming assignment has been released on BB. It is centred around priority queues, a subject that will be treated mainly after the winter break. The deadline is April 4.\nAlso Assignment 3 has been released. Please don't forget that its deadline is the same as the one of Assignment 2 (March 7), so use your time wisely.\n",
        "Due to multiple requests the deadline for Assignment 2 has been changed to the end of the first week after the winter break.\nHowever, this will be also the deadline for Assignment 3. So we strongly advise that you do as much as possible on Assignment 2 before the break in order not to run into time problems in the first week after the break.\n",
        "Office Hours: Wednesday 15:00-17:00 (except in winter vacation)\nGroups: See the previous announcement. So far not many groups have been formed. Please let me know your group members asap. I will let you know the number of your group.\nLabs: Labs start on Monday, January 11. There are four lab groups, each supervised by two teaching assistants. All labs are on Mondays, 18:00-20:00. Afterwards you can continue as long as you are allowed to remain in the room.\nLab1 (Li Xiang, He Shilan) is held in LTN-B304\nLab2 (Wu Mingzhou, Yuan Xinkai) is held in LTN-B404\nLab3 (Jiang Fengqing, Chen Yize) is held in LTN-B434\nLab4 (Xiong Neng, Zhou Qinren) is held in LTN-B333\nIf your group number is n, then take k = n mod 4. You are supposed to be in lab group k. This applies from week 2 onwards. In week 1 (dedicated to C++ introduction) choose any of the four lab rooms, but make sure that no more than 30 students are in one lab.\n",
        "Dear students,\nWelcome to the course CS 225 \"Data Structures\", which will begin next week on January 11. We will have the first lecture and the first labs both on the first Monday.\nAll assignments, programming assignments and the final presentations this semester will be group assignments. For this you need to form groups of 3 or 4 students. Please send the names of your group members by email to me, so I can set up the groups in BB and allocate the TAs and lab groups.\nIf you have problems to find classmates to form a group together with you, you can launch a search for classmates in Piazza or send a message to me, so we can bring you together with other students. Group formation has to be completed before the deadline of the first assignment.\nThe grouping does not apply to the first lab on January 11, which is dedicated to C++. Please choose one of the lab rooms (B304, B404, B434, B333), but make sure that in every room there are no more than 30 students.\nkind regards\nKD Schewe\n",
        "The following test has been made available in Content: Week8 Quiz.\n",
        "Dear Students,\nThis message will give details about the final Listening and Reading exam, final Wiring exam for ZJE students and the final Spoken Presentation assessment. \nAfter consideration and discussion with the Center for Academic Affairs, it has been decided that the final Listening and Reading exam and the Writing exam for ZJE students will be postponed until all students return to campus in time for the Fall/Autumn semester in September.\nThe reason for this decision relates to the broader decision by Academic Affairs for all courses to only give exams that can be carried out online. Exams and assessments which cannot be done online will instead be delayed until sometime in September. \nFor Integrated English 2 this means that the final Listening & Reading exam and the Writing exam will not take place on May 25th as originally planned.\nThis has no effect on the final speaking assessment which remains the same.\nWe understand that this may cause some concern for those students who worry about how this delay will affect their GPA. However, this is something that can be discussed with the Center for Academic Affairs and your institute at a later date.\nFor now, you just need to know that in your IE2 class, the last major task of this semester is to complete your final presentation and submit it before the deadline on the 22nd of May.\nIn the summer vacation period, you should dedicate a little time each week to practice for TOEFL or IELTS tests to prepare for the final exams in September.\nIf you have further questions about the final assessments, please use the QnA forum here on blackboard and we will try to answer you as soon as possible.\n  All the best,\nYour integrated English Instructors\n",
        "In a few hours, the Week 9 content folders will open and it will be ready for your mid-term presentation. The *only* required activity is your midterm presentation in the Speaking/Week 9 folder. This will be your first graded activity in this course.\nYou are strongly encouraged to go back to previous weeks and review lectures, reading tasks, and the reading task responses of your classmates before recording your video.\nIf you have questions, first review the Q&A forum to search if your question has already been answered. If not, you can post a new question.\nPlan ahead and do not wait until the last minute to submit your presentation. Expect technical difficulties and for the network to be slow. The scores of late submissions will be reduced by 5% per day that it is late.\nAs always, you are allowed multiple submissions up to the deadline.\n",
        "Dear students,\nAfter the first few weeks, I have some additional tips and reminders to help the course run more smoothly for all of us.\n1) Do the assigned pre-reading and watch the lesson videos before you do your presentation or writing assignment for the week. Your feedback will be given assuming that you've learned from the lesson materials, so to avoid the embarassment and waste of your time, please prepare yourself appropriately. If it's clear that you did not pay attention to weekly lessons, you will not receive credit for that week's work until you do.\n2) Submit your homework in the correct place. If it is an assignment for Week 4, it belongs in the assignment submission for week 4 and not week 3. If you want credit for your work, it must be in the right place. Please note, also, that your homework submissions are \"SUBMISSIONS\" and not \"COMMENTS.\" It is important to pay attention to where you put your work for it to be managed efficiently. See the image below if you are not sure about the differences between these two terms.\n2.1) Concerning presentation submissions for all students, starting week 5 with Presentation 2, ALL submissions must be via OneDrive with the link as described in this important announcement from week 3. It takes far too long for us to download videos that are submitted as an attachment. Starting week 5, any uploaded/attached presentations will receive an automatic zero until you submit it correctly  by uploading it to OneDrive and linking it. We appreciate your flexibility and support in this. I understand this will be unfamiliar to some of you. Please take the time to familiarize yourself with the education tools your campus provides. I have curated some documentation (in both English and Mandarin) for you to review on a recent Q&A thread. If you need further help with this, please contact IT services for help.\n2.2) Concerning writing submissions for ZJE students, feel free to continue attaching Word documents if this works better for you.\n3) If you experience any technical difficulties, such as not being able to submit an assignment in the right place, let us know immediately via the WeChat group or email, and wait to submit it in the correct place. Many students are submitting work in other, incorrect, weeks/folders without telling us about the problem. This will result in no participation credit for the missing week's material until it is submitted correctly. For example, homework for Week 4 speaking needs to be submitted in the week 4 speaking assignment. If you put it anywhere else, it will get lost and uncounted.\nIf you have any questions or concerns, you may email me at william@intl.zju.edu.cn or contact any of us on the WeChat group. The Q&A forum still works, but the other options often receive a faster response.\nThanks, and keep up the consistent work!\nWill\n",
        "I've opened up a WeChat group for all sections of Integrated English 2 combined. We will continue to use Blackboard as much as possible for submissions, but, this WeChat group will be a more familiar way to connect with us and get support if you have any questions or problems with the course materials or Blackboard.\nJoin us:\nThis should largely replace the Q&A forum, but I suspect all of you will be much more comfortable with WeChat.\n",
        "Some of you may be experiencing an error (\"failure to save message\") when you submit discussion forum posts. We urge you to contact ITS to resolve this. However, I can offer a tip to make sure you don't lose your writing when errors like this happen.\nCompose your response in another app, like Notepad, first, and then copy it over when you're ready. Many things can happen that might erase the information in a webpage textbox, and not all browsers are designed to save what you type.\nHopefully, ITS can provide a solution soon.\nP.S., a couple of things to remember\nA) When asking us, or anyone for that matter, for assistance, please provide enough information for us to understand the problem. We are powerful and magical creatures, but alas we cannot yet read minds. That goes for literally every person you need to ask for assistance: ITS, other professors, your bank,  etc.\nB) If it is not urgent or personal, use the Q&A forum, please! It's much easier to answer a question once and let all students read the question and response than it is to respond to the same issue hundreds of times.\n",
        "Dear Undergraduate Students,\n  Welcome to the new semester and to Integrated English 2. As you know, this semester the university will be running all courses online. I know this adds extra challenges to your studies, but I'm confident that we can make the most of it.\n  Integrated English 2 this semester is going to make use of a range of online tools and methods to deliver English teaching content and training tasks. These are designed specifically for you to improve and practice the English skills you need for academic success.\n  There are a few important things to know about this online course and several points you should consider about.\nHow you will interact with the online course\nMost of the online course will be delivered via blackboard. There are three main ways you will interact with the course materials:\nThe speaking course this semester focuses on Presentation skills.\nThe writing course is about Science report writing.\n  Each week you will have a new set of online tasks to complete. These will include a video lecture to watch. These will be around 20 minutes.\nYou will usually have reading or listening tasks to do; this is similar to last semester but this time you will have to post your answers to tasks on blackboard.\nZJE students will also have extra instruction each week for science writing and will be given a writing practice task each week.\nWe have discussion forums on Blackboard for you to post your answers to tasks. We can then read your responses and where appropriate offer feedback and advice on your English.\n  The discussion forums will be an important point of interaction with your English professors. Through the forum you can ask questions about the course, questions about individual tasks, and you can interact with other students. You can see other students’ work and read feedback from professors. This should help everyone learn things about their English as well as stay in touch with what’s happening with the course.\nHow you will be assessed\nThis semester is a very special case and the assessments might have to change as a result.\nSpeaking: Right now, the plan is to have you complete two speaking assessments online by recording and uploading video recorded spoken presentations. One short talk and one longer presentation with visuals.\nOver the course of the semester, you will submit 3 non-graded practice presentations. You must record these as video files to submit on Blackboard. Instructions on how to do this will be provided.\nFor assessment you will submit 1 graded mid-term recorded presentation, and for your final speaking assessment you will submit a recorded presentation with visual aids (using PowerPoint slides, etc.).\n  Listening and Reading: Right now, we anticipate that by the end of the semester, everyone will have returned to campus and be able to sit the final exam as normal. If that is not the case then we will have to find an alternative way to run the final listening and reading exam online. But this has not been decided yet. So, for now do not worry as much about this test.\nZJE Writing: As was the case last semester, ZJE students will also take the extra writing component of Integrated English 2. The situation for the writing exam is the same as for listening and speaking above\nNow, throughout the semester it is very important that you pay attention to your emails and blackboard announcements and keep track of the tasks and work you are doing to improve your English. Whenever you are unsure what to do, you can ask using blackboard or by sending an email.\n    Head over to the Content section of blackboard and access the week one speaking practice materials to get started.\n  All the best for this unusual and interesting new semester.\n  Sincerely,\nYour English Professors.\n \nCourse Link/Content/Speaking lessons/Week 1: February 17, 2020 -- February 21, 2020\n",
        "The Math 286 Grades are now online. Please refer to the column \"Final Score\" for your total numerical score (0-100), from which the final letter grade (the one which counts at the end of the day) is computed according to a scheme similar to last semester's Math 241. (This scheme will be published soon.)\nI am sorry that yesterday evening, due to upload errors, some inconsistent data may have been on BB. The column \"Total\", if anything, contained the wrong data.\nThe final exam is now rated as 45+7 (full score 45 marks, exactly corresponding to its weight of 45%, and 7 optional marks). Details on this will be published in a revised version of the solutions file. Extra credits are traded in for 5% of the final exam score (whichever relative score is better), and similarly for the homework. The exact spreadsheet formula for the final score is\n40*(E/45)+M+MAX(25*E/45,H)+L+MAX(5*E/45,C)\n(E final exam, M midterm, H homework, L lab, C extra credit)\nHappy Dragon Boat Festival!\nTH\n",
        "Dear Math 286 students,\nplease do me a favor and complete the Math286 course evaluation at\nhttps://forms.office.com/Pages/ResponsePage.aspx?id=xSAmKRCuU0Wsz2jsgDJQCOnMVLQF6hhIhjqiVXqkhG1UNExTN1U5OFZXUUNQWUtHWFM1OTgxWVVaUi4u\nwithin 3 days from now, if you haven't done yet. Your feedback is very important for detecting strenghts/weeknesses of this year's course and improving the course next semester. The last two questions are:\nQ15: Which topic in the course did you find most/least interesting?\nQ16: Where there any prerequisites for the course that you think you didn't have; if ``yes'', which are these?\nMany thanks, TH\n",
        "You can submit your application for a TA position in Calculus III (Math241) in Fall 2021 until Mon May 31 (tomorrow); see Slide 74 of lecture55-56_handout.pdf for more details.\nTH\n",
        "Solutions to the final examination have been uploaded to the usual place. This will be complemented by additional remarks on student solutions (like alternative solutions or common errors) after the grading is done. The marks distribution will also be fixed at that time.\nTH\n",
        "The final examination in Math286 will be held on Fri May 28, 9-12am, in LTW 102, 201, 204. The rules are the same as for the Calculus III final exam last semester; see also Slide 72 of lecture55-46_handout.pdf\nWeight: 45% of the total score; 5% can be replaced by extra credits (if the relative extra-credit score is higher)\nTopics: All topics covered in Lectures 1-54 (no questions on PDE's). There will be no dedicated questions on LInear Algebra and Complex Numbers, but you may need to use knowledge in these fields when answering questions about ODE's.\nOffice hours:  Before the exam I will have office hours on Wed May 26, 10:30 - 12:00, in ZJUI 1C-415. Their purpose is to resolve questions (if any) about the course material you have encountered during (or before) the review period, not to answer any examination-specific questions. (Those should be asked on piazza.com.)\nSeveral of our TA's are conducting Math286 review sessions for their discussion group next week - you are very much encouraged to attend. Date/time/venue will be the same as for the TA office hours (see announcement of Jan 16), unless they have informed you otherwise. If the schedule conflicts with other exams, you are free to switch to another TA.\nThis year's exam will be similar to (but also different from) those in previous years. The two sample final exams I've put in the folder \"Exams\" certainly serve as good preparatory exercises for a major portion of this year's exam. Solutions will be uploaded on the weekend.\nGood luck!\nTH\n",
        "The lecture slides for Lecture 55 and 56 contain 3 important slides at the end, which especially students who didn't attend Lecture 56 should note:\n1. Information on the final exam: The rules will be the same as for the Calculus III final exam; see Slide 72.\n2. Course evaluation: Please do us a favor and complete the online course evaluation form for Math286 this Spring. Click the link on Slide 73 and note the additional questions Q15, Q16.\n3. Call for TA's for my Calculus III course in Fall 2021; see Slide 74.\nSince attendance during the last week was low, I have decided not to ask a question about PDE's in the final exam. But be prepared for a question about the material in Lectures 53, 54.\nTH\n",
        "The time limit of 10 min per work group will be enforced strictly today. Please try to make your presentation short, focus only on selected parts from the report (which you can always quote if necessary), and let only 1or 2 work group members do the presentation.\nNevertheless expect the later talks to be delayed by a certain time, since switching between groups takes a few minutes (based on the experience yesterday). Please avoid such delays, if possible, i.e., by having your USB stick ready if it's your turn or uploading the presentation file in advance.\nTH\n",
        "Lab presentations are scheduled for Mon May 17, 4-6 pm and Tue May 18, 5-8 pm, in LTN-B 424.  Time slots are per discussion group as follows:\nGroup 1 (Niu Yiqun): May 17, 4-5pm\nGroup 2 (Yu Chengting): May 17, 5-6pm\nGroup 3 (Yuan Yue): May 18, 5-6pm\nGroup 4 (Chen Shengjian): May 18, 6-7pm\nGroup 5 (Qin Tianzuo): May 18, 7-8pm\nThe TA's will make the actual presentation schedule. Each work group has 10 min presentation time. You need to be present in LTN-B 424 only for the presentation of your work group. Should there be some conflict with another assignment, get in touch with your TA early and ask for rescheduling the presentation. Work groups can select a single presenter or switch presenters during their talk. The presentation score (5 marks) is always per work group, and likewise for the lab report score (10 marks).\nBefore your presentation you have to hand in the lab report of 6-8 pages (excluding computer printouts). We won't impose the page limit strictly - since it depends on the format -, but obvious breaches of the rule (such as using double-spaced typesetting to reduce the effective length to 2.5 pages, or writing as densely as on the cheating sheet for our final exam in Calculus 3;-) will be penalized.\nBe sure to name all group members and their student id's on the first page of the report, and - this represents a new requirement! - please include the following honorary statement on the first page, signed by each group member:\nWe declare that this report is our own original work, and every work group member has a fair share in this work. For the preparation of the report we have not used any other resources than the Math 286 lecture material and the references cited in the report.\nThe lab problems and basic suggestions for designing your presentation/report can be found in the file lab.pdf in the Math286 root folder. Here is some further advice: Conceive your presentation for someone who has attended Math286 but has no background in numerical solutions of ODE's. That is, you should explain (in a lucid way) the ideas behind the three methods and the key parameters (order, step size, local/global truncation error, etc.). The remaining time can be used for presenting your solution to one or both of the lab problems (for the presentation one problem is enough) and maybe discuss some related aspects of your choice. For the lab report it is mandatory to solve (or at least attempt to solve) both lab problems. Here you should give full details of your solutions, describe the software used, provide a basic error analysis, etc. On the other hand you can reference anything in Chapter 8 of our textbook in the report and need not explain the numerical methods from scratch.\nBest wishes, TH\n",
        "Two final exam samples have been put online (in the folder \"Exams\"). Solutions will be published 1 week before this year's final exam, which is on May 28.\nTH\n",
        "The former exercise H84 in Homework 13 has been replaced by a new (shorter) exercise about the characteristic polynomial of similar matrices. The old exercise, which requires the material on stability of linear systems discussed only in the 2nd half of next week, is now optional (H87).\nThe latest version of Homework 13 contains notes on H81 and H82 b) at the end, which for their solution require material from next week's lectures. My apologies for this oversight!\nTH\n",
        "Because of the heavy workload this week (with midterms on Tue) you can hand in H69 - H72 of Homework 11 together wit Homework 12 on May 6. The TA's will be advised to select for presentation during tomorrow's discussion session only exercises from H66 - H68. Once a solution to an exercise has been presented, however, it is not possible to hand in your own solution to this exercise later.\nI hope this eases the situation a bit. The remaining homework (2 assignments) will be made available soon, so that you can better plan the semester finish. To give you more time, lab presentations will be scheduled only in the last week of the semester (on May 17, 18).\nTH\n",
        "In the lectures on Wed April 28 and Fri April 30 we will start discussing 1st-order ODE systems and the significance of eigenvectors/eigenvalues for their solution. These are core topics of Math 286, and hence for students who have recently missed some lectures a good \"opportunity\" (rather I should say, an obligation) to return to class.\nTH\n",
        "The slides on Linear Algebra (lecture42-45_handout.pdf) contain much more material than we have actually discussed in the lecture. Students who didn't attend one of these lectures should note the relevant topics:\nThe only fields of interest for Math286 are Q, R, C.\nYou are expected to understand the basic Linear Algebra concepts (vector space, linear combination, generating set, linear independence, basis, dimension, subspaces, linear map) in the non-standard setting. Particularly instructive in this regard are the Problem on Slide 27 ff and the example on Slide 32 ff.\nYou should know the Fundamental Theorem of Linear Algebra, the dimension formula for subspaces, direct sums, the dimension formula for linear maps (including \"kernel of a linear map\"), coordinate vectors and change-of-basis matrices.\nTH\n",
        "A new version of Homework 11 has been uploaded. This contains a new optional exercise, H75, on the Laplace transform, a correction and an additional hint to H72, and a clarification of the limit in H69 (the real variable s or, more generally, for a complex variable the real part Re(s) should tend to +infinity).\nTH\n",
        "It has come to my attention that some students are notoriously late with their homework submission. This is against our rules (\"late homework will not be accepted\") and also conflicts with the timely publication of our sample solutions after the deadline. Hence I have advised our TA's to inforce the HW deadline strictly from now on and impose a penalty of at least 50% of the corresponding score in case of violation.\nThanks for your understanding, TH\n",
        "The details of the lab project have been fixed and announced. Look for a file \"Lab project\" in the root folder. TA's will give you more information in today's discussion session, in which also the lab work groups will be formed.\nPlease note that homework assignments (with somewhat reduced work load) will continue until the end of the semester. So you should manage your time accordingly and start working on the lab project early. Lab work groups can meet anywhere at any time.\nTH\n",
        "Discussion Group 1 (Niu Yiqun) today is cancelled and will be moved to a later date. Students of Group 1 should hand in their homework today in LTN A-426 (Qin Tianzuo). About date/time/venue of the makeup session you will be notified by Niu Yiqun on WeChat.\nTH\n",
        "As you know the midterm will be held this Thu April 1, 4:15 - 5:15 pm\nVenues:          ECE students: LTE 102/103;         all others: LTW 102/103\nFormat: Multiple choice, 15 questions, strictly CLOSED BOOK (no electronic devices, no notes, no cheating sheet, etc., only a pen is allowed)\nWeight: 15 % of the total score\nTopics: All topics discussed so far in the lecture and homework. The last relevant topic is \"Euler equations\" (discussed today). The rather technical question whether solutions of Euler equations on (0,oo) can be extended to the whole real line (skipped in today's lecture) will not be required.\nGood luck!\nTH\n",
        "The knowledge of higher-order linear ODE's with constant coefficients required to solve the exercises of Homework 6 is contained in lecture21-24 and will be completely available only after Lecture 24 on Mon Mar 22. However, I am planning to change the order of the material discussed (examples and the homogeneous case on Wed, inhomogeneous case on Fri, proofs and more background on Mon), so that you can do at least the mandatory exercises (except H39 perhaps) after the lecture on Fri.\nTH\n",
        "Now we have a piazza class for Math 286 in Spring 2021. For enrolment please go to\nhttps://piazza.com/intl.zju.edu.cn/spring2021/math286\nAll students are very much encouraged to enrol and ask course related questions there (which you can do anonymously, if you want). You can find the link also in the BB content folder for Math 286 (look for \"Piazza\").\nTH\n",
        "The midterm exam of Math 286 will be held on Thu Apr 1, 4.15 - 5.15 pm.                                                \nWeight: 15% of the total score                                                \n                                                                               \nForm: Multiple Choice Test (15 questions), strictly CLOSED BOOK           \nThere will be no discussion sessions on Apr 1, but you have to hand in your homework as usual.                                                                            \nTH\n",
        "Dear Students,\na happy and healthy New Lunar Year of the Buffalo to all of you!\nI am not quite sure whether all of you are already back on Campus and able to follow the Math 286 Lectures in person. For those who are not yet allowed to come back I have made the lecture videos of last year (back then the course was taught online) available; cf. link in the root folder. Last year's lectures were slightly different, and with different breaks between lectures, but nevertheless they provide a viable alternative route to studying the current material if you can't attend the lecture. Our present topic \"uniform convergence\" (lecture11-13_handout.pdf, covered in Lectures 11-14 until Wed), was discussed last year in Lectures 10-13 (starting at Minute 16 in Lecture 10 and ending at Minute 32 in Lecture 13). The material at the end of lecture11-13_handout.pdf (new for this year) is optional and can be studied directly from the slides.\nIf for the same reason you can't submit your homework in person, you should notify your TA well in advance of your situation. In such cases we will then allow electronic submission until the restriction is lifted.\nBest wishes, TH\n",
        "Homework 3 (due in the week after the holidays) is online now. If you intend to work on it during the next few days, you should download it now, because Blackboard will be unavailable from tomorrow Feb 1 until at least Feb 4.\nHappy and healthy Spring Festival holidays!\nTH\n",
        "Homework 2 is already online. It is a bit lengthy (because of H9) and you are advised to start working on it as soon as you have finished Homework 1. After tomorrow's (Tue) lecture the necessary prerequisites for solving the exercises in Homework 2 will be available, with the exception of H10.\nTH\n",
        "Professor and TA's have weekly office hours.\nThomas Honold, Mon 4-5 pm, ZJUI Building (1C) 415\nYuan Yue, Mon 8-9 pm, LIbrary Cafe\nQin Tianzuo, Tue 6-7 pm, Library Cafe\nChen Shengjian, Tue 7-8 pm, Library Cafe\nYu Chengting, Tue 8-9 pm, Library Cafe\nNiu Yiqun, Sat 1-2 pm, Library Cafe\nOffice hours start next week. You can turn with questions to either of us, i.e., it is not necessary to visit the TA of your discussion session.\nTH\n",
        "DISCUSSION GROUPS for MATH 286 IN Spring 2021\n------------------------------------------------------\nDate/Time/Venue/TA:\nGroup 1, Thu 4-5pm, LTN-A 226, Niu Yiqun\nGroup 2, Thu 4-5pm, LTN-A 301, Yu Chengting\nGroup 3, Thu 4-5pm, LTN-A 325, Yuan Yue\nGroup 4, Thu 4-5pm, LTN-A 401, Chen Shengjian\nGroup 5, Thu 4-5pm, LTN-A 426, Qin Tianzuo\nThe spreadsheet \"list of discussion groups\" in the root folder shows in which group you are.\nThe groups meet weekly, starting on Jan 14 with an introduction of your TA.\nPurpose of the Groups:\n- Hand in your present homework to the respective TA, who will mark it\n- Get back the previous homework\n- Present solutions of previous homework exercises\n- Q/A, announcements, further explanation of particular lecture topics\n  by TA, etc.\nTH\n",
        "Course Link/Content/New class schedule\n",
        "Notice:\n1. In principle, prelab must be completed before class;\n2. Come to lab on time, please. Otherwise you may be recorded and points be deducted;\n3. Use the experimental devices on your own table!\n4. Tidy up your table before leaving lab.\n5. Check the number and states of the devices before and after class.\nCourse Link/Content/prelabs of phys212\n",
        "Phys213 has prelabs, please finish it before class.\n",
        "Notes for Lecture 12 were updated\n",
        "LTW 102  Discussion sections 4,5\nLTW 201 Discussion section 6\nLTE 102 Discussion sections 1-3\n",
        "Midterm will he held this Sunday, April 25th, starting 6 pm. Duration - 2 hours.\nLocations:\nLTE 102   - Discussion groups  1-3,\nLTW 102 -  Discussion groups  4-5,\nLTW 201 -  Discussion group  6\nLecture are rescheduled as follows:\n  Friday, April 23rd - Q/A session, optional\n  Monday, April 26th       - No class\n  Wednesday, April 28th - Lecture 10\n  Friday, April 30th          - Lecture 11\n",
        "Date and time of Midterm exam will be decided today during Discussion sessions.\n",
        "In this course, every student is allowed to create and use HIS OWN hand-written formula sheet (A4, 1 side) during quizzes and exams.\nThe standard Formula sheet will not be provided.\n",
        "Attention! For the next to weeks, the lectures are scheduled as follows:\nFriday, April 2nd - No lecture\nWednesday, April 7th - Lecture 3\nFriday, April 9th - Lecture 4\nDon't forget to complete pre-lectures and checkpoints at Smart.Physics in time.\n",
        "Lectures start next Monday, March 29\nEast Hall, 10:00-11:00\n",
        "Dear all,\nPhys214 lab1 will be in room E417 of lab building, please note.\nThe rest 3 lessons will be in E521/E519.\n",
        "Dear all,\nThe first lab lesson will be on next week, please note.\nNo prelabs for phys214 lab.\nCourse Link/Content/phys214 lab class schedule\n",
        "Dear ALL,\nPlease help finish the course evaluation through the link below.\nhttps://forms.office.com/Pages/ResponsePage.aspx?id=xSAmKRCuU0Wsz2jsgDJQCOnMVLQF6hhIhjqiVXqkhG1UNExTN1U5OFZXUUNQWUtHWFM1OTgxWVVaUi4u\nAnyone who finishes the evaluation and send the screen shot (after you finish it) to your Teaching Assistant through email (only email is acceptable, other ways, such as wechat or others are not acceptable ), will get 0.5 extra point for your final exam. The deadline is 16 May, 5pm.\nThanks\nWenchao CHEN\n",
        "Dear All,\nThe final exam is scheduled on   April 23, 6pm-8pm. \nExam rooms and seats are arranged as in the attached file (in the \"content\"), please find your room and seat number.\nFor those who have conflicts, I already contact you individually to secure another time slot. \nThere are some tips/rules for you.\n1.No cheating sheet, no draft paper are allowed. I will prepare the formula sheet for you.\n2. No electronics besides calculator. \n3. Don't be late. There will be no make-up exam. If you don't come, it will be considered as you give up.\n4.Final exam example is also posted for you reference.\nIf you have any question, contact me through wenchaochen@zju.edu.cn\nWenchao CHEN\n",
        "Dear ALL,\nSince some of you have conflicts on   April 16th. We have to tentatively reschedule the final exam on April 23, 6pm-8pm. If you have any conflict, please contact me through wenchaochen@zju.edu.cn.\nThanks\nWenchao CHEN\n",
        "Dear ALL,\nThe final exam is tentatively scheduled on April 16th, Friday, from 6:00pm to 8:00pm. If you have any conflicts, contact me before April 2ed through wenchaochen@zju.edu.cn\nThanks\nWenchao CHEN\n",
        "Dear ALL\nThe midterm will be on Friday 6-7:20pm. Please attend on time. If you don't attend, that will be considered as \"you give up the midterm exam\", and no make-up exam will be made.\nThanks\nWenchao Chen\n",
        "Dear ALL,\nThe midterm is scheduled on March 19, 6pm-7:20pm, in Lecture Theater East 102; 201; 204. Midterm exam covers Lecture 1-12.\nGood Luck.\nWenchao CHEN\n",
        "Dear All,\nMidterm Term Exam is scheduled on March 19,Friday, 6pm-7:20pm, which covers Lecture 1- 12, Location will be announced later.\n",
        "Dear ALL,\nPlease log into: https://smart.physics.illinois.edu/\nCheck whether you are enrolled in PHY214 or not. If you have problem, contact me before Wednesday.\nEmail: wenchaochen@zju.edu.cn\nWenchao CHEN\n",
        "Dear students,\nPlease fill the form through\nhttps://f.wps.cn/w/cXci677W/  or  with the link in the Wechat group.\nIf you have class on the evening of April 23.\nThanks\n",
        "Office hour is from 4pm to 4:40 pm on Monday. Send an email before you come in case I am not in office.\nOffice: ZJUI Building B 410\n",
        "Dear all,\nPlease print the discussion material before the discussion session or use your tablet.\nThank you.\n",
        "如果你登录系统有问题，找不到课程尽快联系我 https://smart.physics.illinois.edu/\n提供你的名字，uiuc NetID，发我邮箱。\nEmail: wenchaochen@zju.edu.cn\n这周五以后不再受理！\nWenchao CHEN\n",
        "Hi there, we residential college starts our online course now.\nHere, you can view virous interesting courses related to RC, hope you can enjoy it and don't hesitate to reserve and give us a thumb up :)\n"
    ]
}
]
module.exports={
	data:data
}